Repository kubernetes-sigs/headlamp, pull requests merged in 2024-11, with the labels that each got.

#2486 frontend: Use multiple queries in useKubeObjectList and add support for allowedNamespaces
  frontend/src/helpers/testHelpers.ts
  frontend/src/lib/k8s/KubeObject.ts
  frontend/src/lib/k8s/api/v2/hooks.ts
  frontend/src/lib/k8s/api/v2/makeUrl.test.ts
  frontend/src/lib/k8s/api/v2/makeUrl.ts
  frontend/src/lib/k8s/api/v2/useKubeObjectList.test.ts
  frontend/src/lib/k8s/api/v2/useKubeObjectList.ts
  frontend/src/lib/k8s/api/v2/webSocket.ts
  frontend/src/lib/k8s/event.ts
Labels: bug, frontend, regression, size:XL, lgtm, multi

#2503 frontend KubeObject: Fix missing scale api in apiEndpoint getter
  frontend/src/lib/k8s/KubeObject.ts
Labels: bug, frontend, regression, size:S, lgtm

#2516 frontend: Fix missing cluster fields in list views for multi cluster
  frontend/src/components/cluster/Overview.tsx
  frontend/src/components/node/List.tsx
  frontend/src/components/resourceQuota/List.tsx
  frontend/src/components/webhookconfiguration/ValidatingWebhookConfigList.tsx
Labels: bug, frontend, size:XS, lgtm, multi

#2521 frontend: Overview: Add cluster field for multi cluster
  frontend/src/components/replicaset/List.tsx
  frontend/src/components/workload/Overview.tsx
Labels: bug, frontend, size:XS, lgtm, multi

#2523 frontend AuthChooser: Fix incorrect UI flashing
  frontend/src/components/authchooser/index.tsx
Labels: size:XS, lgtm

#2525 app: container: Bump static plugin versions
  app/app-build-manifest.json
  container/build-manifest.json
Labels: plugins, app, container, size:XS, lgtm

#2458 docs: Add new contributors guide
  docs/contributing.md
Labels: documentation, size:L, lgtm

#2522 Fix home constant update
  frontend/src/components/App/Home/index.tsx
  frontend/src/lib/k8s/event.ts
  frontend/src/lib/k8s/index.ts
Labels: size:L, lgtm

#2528 frontend Map: Fix breadcrumb link causing navigation in electron app
  frontend/src/components/resourceMap/SelectionBreadcrumbs.tsx
Labels: size:XS, lgtm

#2511 frontend: clusterApi: Fix testClusterHealth for multi cluster
  frontend/src/lib/k8s/api/v1/apiProxy.test.ts
  frontend/src/lib/k8s/api/v1/clusterApi.ts
Labels: bug, frontend, size:S, lgtm, multi

#2527 frontend: Home: Add label for actions menu
  frontend/src/components/App/Home/index.tsx
Labels: frontend, a11y, size:S, lgtm

#2532 Fix push release assets
  app/package-lock.json
  app/package.json
  app/scripts/push-release-assets/package-lock.json
  app/scripts/push-release-assets/package.json
  app/scripts/push-release-assets/push-release-assets.js
Labels: size:S, lgtm

#2502 Clarify loading of kubeconfig for in-cluster headlamp installations
  docs/installation/in-cluster/index.md
Labels: size:S, lgtm

#2542 chocolatey: Bump Headlamp version to 0.26.0
  app/windows/chocolatey/headlamp.nuspec
  app/windows/chocolatey/tools/chocolateyinstall.ps1
Labels: size:XS, lgtm

#2536 frontend: Home: Show the origin of each cluster
  frontend/src/components/App/Home/index.tsx
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/pt/translation.json
Labels: frontend, size:M, lgtm

#2538 frontend: Improve Map performance
  frontend/src/components/resourceMap/GraphView.tsx
  frontend/src/components/resourceMap/graph/graphFiltering.test.ts
  frontend/src/components/resourceMap/graph/graphFiltering.ts
  frontend/src/components/resourceMap/graph/graphGrouping.tsx
  frontend/src/components/resourceMap/graph/graphLookup.test.ts
  frontend/src/components/resourceMap/graph/graphLookup.ts
  frontend/src/components/resourceMap/sources/GraphSources.tsx
Labels: size:L, lgtm

#2555 docs: Add publishing guide
  docs/development/plugins/images/plugin-guide-add-repo.png
  docs/development/plugins/images/plugin-on-plugin-catalog.png
  docs/development/plugins/images/plugin-repo-add-repo-button.png
  docs/development/plugins/publishing.md
Labels: documentation, size:L

#2543 frontend: Home: Improve cluster origin labels
  frontend/src/components/App/Home/index.tsx
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/pt/translation.json
Labels: frontend, size:S, lgtm

#2576 docs: Update Community Call
  docs/contributing.md
Labels: size:XS, lgtm

#2582 charts: Fix storageClassName in pvc
  charts/headlamp/templates/pvc.yaml
Labels: size:XS, lgtm

#2562 frontend: Enable allowProposedApi in XTerminal
  frontend/src/components/common/LogViewer.tsx
  frontend/src/components/common/Terminal.tsx
Labels: size:XS, lgtm

#2587 headlamp-plugin: Run npm install in update deps script
  plugins/headlamp-plugin/package.json
Labels: bug, plugins, headlamp-plugin, size:XS, lgtm

#2578 frontend: plugin: Sync plugin version with backend
  frontend/src/plugin/index.ts
Labels: bug, plugins, size:XS, lgtm

#2574 frontend: Add global search
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/App/TopBar.tsx
  frontend/src/components/App/__snapshots__/TopBar.NoToken.stories.storyshot
  frontend/src/components/App/__snapshots__/TopBar.OneCluster.stories.storyshot
  frontend/src/components/App/__snapshots__/TopBar.ProcessorAction.stories.storyshot
  frontend/src/components/App/__snapshots__/TopBar.Token.stories.storyshot
  frontend/src/components/App/__snapshots__/TopBar.TwoCluster.stories.storyshot
  frontend/src/components/globalSearch/Delayed.tsx
  frontend/src/components/globalSearch/GlobalSearch.stories.tsx
  frontend/src/components/globalSearch/GlobalSearch.tsx
  frontend/src/components/globalSearch/GlobalSearchContent.tsx
  frontend/src/components/globalSearch/__snapshots__/GlobalSearch.BasicExample.stories.storyshot
  frontend/src/components/globalSearch/useLocalStorageState.tsx
  frontend/src/components/globalSearch/useRecent.tsx
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/plugin/__snapshots__/pluginLib.snapshot
  frontend/src/redux/actionButtonsSlice.ts
Labels: size:XXL, lgtm

#2566 frontend: Job: Add sort function for job durations
  frontend/src/components/job/List.tsx
Labels: bug, frontend, size:XS, lgtm

#2592 frontend: Add tests for useWatchKubeObjectLists
  frontend/src/lib/k8s/api/v2/useKubeObjectList.test.ts
  frontend/src/lib/k8s/api/v2/useKubeObjectList.test.tsx
  frontend/src/lib/k8s/api/v2/useKubeObjectList.ts
Labels: size:L, lgtm

#2609 frontend: add resource name to SectionHeader
  frontend/src/components/common/Resource/MainInfoSection/MainInfoSectionHeader.tsx
  frontend/src/components/configmap/__snapshots__/Details.Empty.stories.storyshot
  frontend/src/components/configmap/__snapshots__/Details.WithBase.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceDefinition.Details.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceDetails.NoError.stories.storyshot
  frontend/src/components/cronjob/__snapshots__/CronJobDetails.EveryAst.stories.storyshot
  frontend/src/components/cronjob/__snapshots__/CronJobDetails.EveryMinute.stories.storyshot
  frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPADetails.Default.stories.storyshot
  frontend/src/components/ingress/__snapshots__/ClassDetails.Basic.stories.storyshot
  frontend/src/components/ingress/__snapshots__/ClassDetails.WithDefault.stories.storyshot
  frontend/src/components/ingress/__snapshots__/Details.WithResource.stories.storyshot
  frontend/src/components/ingress/__snapshots__/Details.WithTLS.stories.storyshot
  frontend/src/components/ingress/__snapshots__/Details.WithWildcardTLS.stories.storyshot
  frontend/src/components/lease/__snapshots__/Details.LeaseDetail.stories.storyshot
  frontend/src/components/limitRange/__snapshots__/Details.LimitRangeDetail.stories.storyshot
  frontend/src/components/namespace/__snapshots__/NamespaceDetails.Active.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.Error.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.Initializing.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.LivenessFailed.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.PullBackOff.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.Running.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.Successful.stories.storyshot
  frontend/src/components/podDisruptionBudget/__snapshots__/pdbDetails.Default.stories.storyshot
  frontend/src/components/priorityClass/__snapshots__/priorityClassDetails.Default.stories.storyshot
  frontend/src/components/resourceQuota/__snapshots__/resourceQuotaDetails.Default.stories.storyshot
  frontend/src/components/runtimeClass/__snapshots__/Details.Base.stories.storyshot
  frontend/src/components/secret/__snapshots__/Details.Empty.stories.storyshot
  frontend/src/components/secret/__snapshots__/Details.WithBase.stories.storyshot
  frontend/src/components/storage/__snapshots__/ClaimDetails.Base.stories.storyshot
  frontend/src/components/storage/__snapshots__/ClassDetails.Base.stories.storyshot
  frontend/src/components/storage/__snapshots__/VolumeDetails.Base.stories.storyshot
  frontend/src/components/verticalPodAutoscaler/__snapshots__/VPADetails.Default.stories.storyshot
  frontend/src/components/webhookconfiguration/__snapshots__/MutatingWebhookConfigDetails.WithService.stories.storyshot
  frontend/src/components/webhookconfiguration/__snapshots__/MutatingWebhookConfigDetails.WithURL.stories.storyshot
  frontend/src/components/webhookconfiguration/__snapshots__/ValidatingWebhookConfigDetails.WithService.stories.storyshot
  frontend/src/components/webhookconfiguration/__snapshots__/ValidatingWebhookConfigDetails.WithURL.stories.storyshot
Labels: size:M, lgtm

#2610 frontend: AuthVisible: Validate verb before auth check
  frontend/src/components/common/Resource/AuthVisible.tsx
Labels: frontend, auth, size:S, lgtm

#2608 frontend: cleanup general settings
  frontend/src/components/App/Settings/Settings.tsx
  frontend/src/components/App/Settings/ThemeChangeButton.tsx
  frontend/src/components/App/Settings/__snapshots__/Settings.General.stories.storyshot
  frontend/src/components/common/TimezoneSelect/TimezoneSelect.tsx
  frontend/src/i18n/LocaleSelect/LocaleSelect.tsx
  frontend/src/i18n/LocaleSelect/__snapshots__/LocaleSelect.Initial.stories.storyshot
Labels: size:M, lgtm
