Repository kubernetes-sigs/headlamp, pull requests merged in 2024-12, with the labels that each got.

#2629 frontend Map: Fix border on the side details panel
  frontend/src/components/resourceMap/details/GraphNodeDetails.tsx
Labels: size:XS

#2631 frontend: AuthChooser: Add home navigation on auth fail
  frontend/src/components/authchooser/AuthChooser.stories.tsx
  frontend/src/components/authchooser/__snapshots__/AuthChooser.AnError.stories.storyshot
  frontend/src/components/authchooser/__snapshots__/AuthChooser.AuthTypeoidc.stories.storyshot
  frontend/src/components/authchooser/__snapshots__/AuthChooser.BasicAuthChooser.stories.storyshot
  frontend/src/components/authchooser/__snapshots__/AuthChooser.Testing.stories.storyshot
  frontend/src/components/authchooser/index.tsx
Labels: frontend, size:L, lgtm

#2616 frontend: ClusterChooserPopUp: Fix dark mode visibility
  frontend/src/components/cluster/ClusterChooserPopup.tsx
Labels: bug, frontend, size:S

#2619 readme: Update header image and format
  README.md
Labels: documentation, size:S, lgtm

#2615 frontend: refactor settings cluster
  frontend/src/components/App/Settings/AllowedNamespaces.tsx
  frontend/src/components/App/Settings/CustomClusterName.tsx
  frontend/src/components/App/Settings/DefaultNamespace.tsx
  frontend/src/components/App/Settings/SettingsCluster.tsx
Labels: size:XL, lgtm

#2636 frontend: fix nullable node status
  frontend/src/components/cluster/Charts.tsx
  frontend/src/components/cluster/__snapshots__/Overview.Events.stories.storyshot
  frontend/src/components/node/Details.tsx
  frontend/src/components/node/List.stories.tsx
  frontend/src/components/node/List.tsx
  frontend/src/components/node/__snapshots__/List.Nodes.stories.storyshot
  frontend/src/components/node/storyHelper.ts
  frontend/src/lib/k8s/node.ts
  frontend/src/lib/util.ts
Labels: size:L

#2635 i18n: Update Chinese (Traditional) translation for glossary.json and translation.json
  frontend/src/i18n/locales/zh-tw/glossary.json
  frontend/src/i18n/locales/zh-tw/translation.json
Labels: i18n, size:XL, lgtm

#2620 frontend: Improve Table performance and update styles
  frontend/src/components/App/Home/index.tsx
  frontend/src/components/App/PluginSettings/__snapshots__/PluginSettings.DefaultSaveEnable.stories.storyshot
  frontend/src/components/App/PluginSettings/__snapshots__/PluginSettings.EmptyHomepageItems.stories.storyshot
  frontend/src/components/App/PluginSettings/__snapshots__/PluginSettings.FewItems.stories.storyshot
  frontend/src/components/App/PluginSettings/__snapshots__/PluginSettings.ManyItems.stories.storyshot
  frontend/src/components/App/PluginSettings/__snapshots__/PluginSettings.MoreItems.stories.storyshot
  frontend/src/components/common/Resource/ResourceTable.tsx
  frontend/src/components/common/Resource/__snapshots__/ResourceListView.OneHiddenColumn.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/ResourceTable.NameSearch.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/ResourceTable.NoFilter.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/ResourceTable.WithHiddenCols.stories.storyshot
  frontend/src/components/common/Table/Table.tsx
  frontend/src/components/common/Table/__snapshots__/Table.Datum.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.Getter.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.LabelSearch.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.NameSearch.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.NamespaceSearch.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.NamespaceSelect.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.NotFoundMessage.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.NumberSearch.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.ReflectInURL.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.ReflectInURLWithPrefix.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.UIDSearch.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.WithFilterMultiSelect.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.WithGlobalFilter.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.WithSorting.stories.storyshot
  frontend/src/components/configmap/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceDefinition.Details.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceDefinition.List.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceList.List.stories.storyshot
  frontend/src/components/daemonset/__snapshots__/List.DaemonSets.stories.storyshot
  frontend/src/components/endpoints/__snapshots__/EndpointList.Items.stories.storyshot
  frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPAList.Items.stories.storyshot
  frontend/src/components/ingress/__snapshots__/ClassList.Items.stories.storyshot
  frontend/src/components/ingress/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/job/__snapshots__/JobList.Items.stories.storyshot
  frontend/src/components/lease/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/limitRange/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/namespace/__snapshots__/NamespaceList.Regular.stories.storyshot
  frontend/src/components/node/__snapshots__/List.Nodes.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodList.Items.stories.storyshot
  frontend/src/components/podDisruptionBudget/__snapshots__/pdbList.Items.stories.storyshot
  frontend/src/components/priorityClass/__snapshots__/priorityClassList.Items.stories.storyshot
  frontend/src/components/replicaset/__snapshots__/List.ReplicaSets.stories.storyshot
  frontend/src/components/resourceQuota/__snapshots__/resourceQuotaList.Items.stories.storyshot
  frontend/src/components/runtimeClass/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/secret/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/ClaimList.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/ClassList.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/VolumeList.Items.stories.storyshot
  frontend/src/components/verticalPodAutoscaler/__snapshots__/VPAList.List.stories.storyshot
  frontend/src/components/webhookconfiguration/__snapshots__/MutatingWebhookConfigList.Items.stories.storyshot
  frontend/src/components/webhookconfiguration/__snapshots__/ValidatingWebhookConfigList.Items.stories.storyshot
Labels: frontend, performance, size:XXL, lgtm

#2626 frontend: Avoid keeping dialogs mounted
  frontend/src/components/App/Home/index.tsx
  frontend/src/components/App/Notifications/index.tsx
  frontend/src/components/App/TopBar.tsx
  frontend/src/components/App/__snapshots__/TopBar.OneCluster.stories.storyshot
  frontend/src/components/App/__snapshots__/TopBar.TwoCluster.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarClosed.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarOpen.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.SelectedItemWithSidebarOmitted.stories.storyshot
  frontend/src/components/common/Dialog.tsx
  frontend/src/components/common/Resource/__snapshots__/EditorDialog.EditorDialogWithResourceClosed.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/ViewButton.View.stories.storyshot
  frontend/src/components/common/Terminal.tsx
  frontend/src/components/pod/__snapshots__/PodDetails.Error.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.Initializing.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.LivenessFailed.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.PullBackOff.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.Running.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.Successful.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodLogs.Logs.stories.storyshot
Labels: frontend, performance, size:XXL, lgtm

#2644 backend: Disable websocket multiplexer
  backend/cmd/headlamp.go
Labels: size:XS

#2611 plugins: Fix vitest placeholder type
  plugins/headlamp-plugin/vite-types.d.ts
Labels: bug, frontend, size:XS, lgtm

#2617 frontend: Add missing isNamespaced property to Custom Resource class
  frontend/src/lib/k8s/crd.ts
Labels: frontend, regression, size:XS

#2645 frontend: i18n: Add missing translations
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
Labels: frontend, i18n, size:L, lgtm

#2604 frontend: Node: Fix table columns and empty values
  frontend/src/components/node/List.tsx
  frontend/src/components/node/__snapshots__/List.Nodes.stories.storyshot
  frontend/src/components/node/utils.tsx
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
Labels: frontend, Table, size:S, lgtm

#2627 frontend: Populate query cache when kubeObject is passed into a Link
  frontend/src/components/common/Link.tsx
  frontend/src/components/workload/Overview.tsx
  frontend/src/lib/k8s/api/v2/hooks.ts
Labels: frontend, performance, size:M, lgtm

#2600 frontend: Rewrite useQueryParamsState logic and add unit tests
  frontend/src/components/resourceMap/useQueryParamsState.test.tsx
  frontend/src/components/resourceMap/useQueryParamsState.tsx
Labels: bug, frontend, size:L, lgtm

#2648 frontend Table: Add support for column selection
  frontend/src/components/App/PluginSettings/__snapshots__/PluginSettings.DefaultSaveEnable.stories.storyshot
  frontend/src/components/App/PluginSettings/__snapshots__/PluginSettings.EmptyHomepageItems.stories.storyshot
  frontend/src/components/App/PluginSettings/__snapshots__/PluginSettings.FewItems.stories.storyshot
  frontend/src/components/App/PluginSettings/__snapshots__/PluginSettings.ManyItems.stories.storyshot
  frontend/src/components/App/PluginSettings/__snapshots__/PluginSettings.MoreItems.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/ResourceListView.OneHiddenColumn.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/ResourceTable.NameSearch.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/ResourceTable.NoFilter.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/ResourceTable.WithHiddenCols.stories.storyshot
  frontend/src/components/common/Table/Table.tsx
  frontend/src/components/common/Table/__snapshots__/Table.Datum.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.Getter.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.LabelSearch.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.NameSearch.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.NamespaceSearch.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.NamespaceSelect.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.NotFoundMessage.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.NumberSearch.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.ReflectInURL.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.ReflectInURLWithPrefix.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.UIDSearch.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.WithFilterMultiSelect.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.WithGlobalFilter.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.WithSorting.stories.storyshot
  frontend/src/components/configmap/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceDefinition.Details.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceDefinition.List.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceList.List.stories.storyshot
  frontend/src/components/daemonset/__snapshots__/List.DaemonSets.stories.storyshot
  frontend/src/components/endpoints/__snapshots__/EndpointList.Items.stories.storyshot
  frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPAList.Items.stories.storyshot
  frontend/src/components/ingress/__snapshots__/ClassList.Items.stories.storyshot
  frontend/src/components/ingress/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/job/__snapshots__/JobList.Items.stories.storyshot
  frontend/src/components/lease/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/limitRange/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/namespace/__snapshots__/NamespaceList.Regular.stories.storyshot
  frontend/src/components/node/__snapshots__/List.Nodes.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodList.Items.stories.storyshot
  frontend/src/components/podDisruptionBudget/__snapshots__/pdbList.Items.stories.storyshot
  frontend/src/components/priorityClass/__snapshots__/priorityClassList.Items.stories.storyshot
  frontend/src/components/replicaset/__snapshots__/List.ReplicaSets.stories.storyshot
  frontend/src/components/resourceQuota/__snapshots__/resourceQuotaList.Items.stories.storyshot
  frontend/src/components/runtimeClass/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/secret/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/ClaimList.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/ClassList.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/VolumeList.Items.stories.storyshot
  frontend/src/components/verticalPodAutoscaler/__snapshots__/VPAList.List.stories.storyshot
  frontend/src/components/webhookconfiguration/__snapshots__/MutatingWebhookConfigList.Items.stories.storyshot
  frontend/src/components/webhookconfiguration/__snapshots__/ValidatingWebhookConfigList.Items.stories.storyshot
Labels: frontend, size:XL, lgtm

#2649 frontend Map: Remember zoom mode. Move viewport logic to useGraphViewport hook
  frontend/src/components/resourceMap/GraphControls.tsx
  frontend/src/components/resourceMap/GraphRenderer.tsx
  frontend/src/components/resourceMap/GraphView.tsx
  frontend/src/components/resourceMap/graphConstants.ts
  frontend/src/components/resourceMap/useGraphViewport.ts
Labels: frontend, size:L, lgtm, resourceMap

#2659 frontend: Add uncommitted i18n changes
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
Labels: size:S

#2594 frontend: allow multiple deletes on ResourceTable
  frontend/src/components/common/ConfirmDialog.tsx
  frontend/src/components/common/Resource/DeleteMultipleButton.tsx
  frontend/src/components/common/Resource/ResourceListView.tsx
  frontend/src/components/common/Resource/ResourceTable.tsx
  frontend/src/components/common/Resource/ResourceTableMultiActions.tsx
  frontend/src/components/common/Resource/__snapshots__/ResourceListView.OneHiddenColumn.stories.storyshot
  frontend/src/components/common/Resource/index.test.ts
  frontend/src/components/configmap/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceDefinition.Details.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceDefinition.List.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceList.List.stories.storyshot
  frontend/src/components/daemonset/__snapshots__/List.DaemonSets.stories.storyshot
  frontend/src/components/endpoints/__snapshots__/EndpointList.Items.stories.storyshot
  frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPAList.Items.stories.storyshot
  frontend/src/components/ingress/__snapshots__/ClassList.Items.stories.storyshot
  frontend/src/components/ingress/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/job/__snapshots__/JobList.Items.stories.storyshot
  frontend/src/components/lease/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/limitRange/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/namespace/__snapshots__/NamespaceList.Regular.stories.storyshot
  frontend/src/components/node/__snapshots__/List.Nodes.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodList.Items.stories.storyshot
  frontend/src/components/podDisruptionBudget/__snapshots__/pdbList.Items.stories.storyshot
  frontend/src/components/priorityClass/__snapshots__/priorityClassList.Items.stories.storyshot
  frontend/src/components/replicaset/__snapshots__/List.ReplicaSets.stories.storyshot
  frontend/src/components/resourceQuota/__snapshots__/resourceQuotaList.Items.stories.storyshot
  frontend/src/components/runtimeClass/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/secret/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/ClaimList.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/ClassList.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/VolumeList.Items.stories.storyshot
  frontend/src/components/verticalPodAutoscaler/__snapshots__/VPAList.List.stories.storyshot
  frontend/src/components/webhookconfiguration/__snapshots__/MutatingWebhookConfigList.Items.stories.storyshot
  frontend/src/components/webhookconfiguration/__snapshots__/ValidatingWebhookConfigList.Items.stories.storyshot
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/plugin/__snapshots__/pluginLib.snapshot
  frontend/src/redux/headlampEventSlice.ts
Labels: size:XXL

#2660 frontend: i18n: Add more missing translations
  frontend/src/i18n/locales/zh-tw/translation.json
Labels: frontend, i18n, size:XS, lgtm

#2662 CI: disable test plugins steps
  .github/workflows/frontend.yml
Labels: size:XS

#2667 frontend: PluginSettings: Fix non responsive enable toggle
  frontend/src/components/App/PluginSettings/PluginSettings.tsx
Labels: regression, size:XS, lgtm

#2661 frontend: Small table fixes and improvements
  frontend/src/components/common/Resource/ResourceTable.tsx
  frontend/src/components/common/Resource/__snapshots__/ResourceListView.OneHiddenColumn.stories.storyshot
  frontend/src/components/common/Table/Table.tsx
  frontend/src/components/configmap/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceDefinition.Details.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceDefinition.List.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceList.List.stories.storyshot
  frontend/src/components/daemonset/__snapshots__/List.DaemonSets.stories.storyshot
  frontend/src/components/endpoints/__snapshots__/EndpointList.Items.stories.storyshot
  frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPAList.Items.stories.storyshot
  frontend/src/components/ingress/__snapshots__/ClassList.Items.stories.storyshot
  frontend/src/components/ingress/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/job/__snapshots__/JobList.Items.stories.storyshot
  frontend/src/components/lease/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/limitRange/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/namespace/__snapshots__/NamespaceList.Regular.stories.storyshot
  frontend/src/components/node/__snapshots__/List.Nodes.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodList.Items.stories.storyshot
  frontend/src/components/podDisruptionBudget/__snapshots__/pdbList.Items.stories.storyshot
  frontend/src/components/priorityClass/__snapshots__/priorityClassList.Items.stories.storyshot
  frontend/src/components/replicaset/__snapshots__/List.ReplicaSets.stories.storyshot
  frontend/src/components/resourceQuota/__snapshots__/resourceQuotaList.Items.stories.storyshot
  frontend/src/components/role/List.tsx
  frontend/src/components/runtimeClass/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/secret/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/ClaimList.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/ClassList.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/VolumeList.Items.stories.storyshot
  frontend/src/components/verticalPodAutoscaler/__snapshots__/VPAList.List.stories.storyshot
  frontend/src/components/webhookconfiguration/__snapshots__/MutatingWebhookConfigList.Items.stories.storyshot
  frontend/src/components/webhookconfiguration/__snapshots__/ValidatingWebhookConfigList.Items.stories.storyshot
Labels: bug, frontend, regression, lgtm

#2650 frontend: LogViewer: Fix log not expanding on full screen
  frontend/src/components/common/LogViewer.tsx
Labels: regression, size:S

#2672 *-build-manifest: Update plugins to the latest versions
  app/app-build-manifest.json
  container/build-manifest.json
Labels: size:XS

#2673 app: Update cross-spawn dependency using npm audit fix
  app/package-lock.json
Labels: size:XS

#2668 frontend: Sidebar: Filter out hidden routes
  frontend/src/components/Sidebar/prepareRoutes.ts
Labels: frontend, size:XS

#2688 frontend DeleteMultipleButton: Fix typo in bulk deletion
  frontend/src/components/common/Resource/DeleteMultipleButton.tsx
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
Labels: size:S

#2684 app: Bump Chocolatey to Headlamp 0.27.0
  app/windows/chocolatey/headlamp.nuspec
  app/windows/chocolatey/tools/chocolateyinstall.ps1
Labels: size:XS

#2678 frontend: Fix memoization for Head cell when selecting all rows
  frontend/src/components/common/Table/Table.tsx
Labels: bug, frontend, size:S

#2696 frontend: Mark http field in IngressRule as optional and fix type errors
  frontend/src/components/ingress/Details.tsx
  frontend/src/components/ingress/List.tsx
  frontend/src/components/resourceMap/sources/definitions/networkSource.tsx
  frontend/src/lib/k8s/ingress.ts
Labels: size:M

#2639 charts: fix: allow env vars to be set when reading others from secrets
  charts/headlamp/templates/deployment.yaml
Labels: size:XS

#2702 backend: Fix cluster addition
  backend/cmd/stateless.go
Labels: size:XS

#2568 headlamp-plugin: Use npm ci to pin deps
  plugins/headlamp-plugin/install-dependencies.sh
  plugins/headlamp-plugin/test-plugins-examples.sh
Labels: dependencies, security, size:XS, lgtm

#2692 frontend: k8s: Sort namespaces in UI
  frontend/src/components/common/NamespacesAutocomplete.tsx
Labels: frontend, namespaces, size:XS

#2691 workflows: Add automation for choco upgrade
  .github/workflows/pr-to-update-choco.yml
Labels: enhancement, size:L, lgtm

#2677 frontend: Fix column visibility handled by internal Table state
  frontend/src/components/common/Table/Table.tsx
Labels: bug, frontend, size:M

#2685 docs: Remove the individual mention of the monthly call event
  docs/contributing.md
Labels: size:XS

#2680 frontend: Add CssBaseline component for improved default styles
  frontend/src/components/App/Layout.tsx
Labels: enhancement, frontend, size:XS, lgtm

#2694 frontend: fix location import on mutli delete button
  frontend/src/components/common/Resource/DeleteMultipleButton.tsx
Labels: size:XS

#2674 frontend: ActionsNotifier: Adjust keys for snackbars
  frontend/src/components/common/ActionsNotifier.tsx
Labels: frontend, size:S, lgtm

#2690 docs(platforms): Add support for Red Hat OpenShift
  docs/platforms.md
Labels: size:XS

#2697 frontend: Fix useKubeObjectLists when deselecting namespaces
  frontend/src/lib/k8s/api/v2/useKubeObjectList.test.tsx
  frontend/src/lib/k8s/api/v2/useKubeObjectList.ts
Labels: size:M, lgtm

#2706 charts: Fix pvc storage requirement
  charts/headlamp/templates/pvc.yaml
Labels: bug, size:XS, lgtm

#2570 backend: Fix reloading of clusters in kubeconfig
  backend/pkg/kubeconfig/file_test.go
  backend/pkg/kubeconfig/watcher.go
  backend/pkg/kubeconfig/watcher_test.go
Labels: bug, backend, size:L, lgtm
