Repository kubernetes-sigs/headlamp, pull requests merged in 2025-07, with the labels that each got.

#3544 frontend: Use simple-eval for advanced search
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/advancedSearch/utils/searchWithQuery.tsx
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: frontend, lgtm, cncf-cla: yes, approved, size/M

#3538 frontend: AlertNotification: Update Storybook with new stories
  frontend/src/components/common/AlertNotification.stories.tsx
  frontend/src/components/common/__snapshots__/AlertNotification.ErrorOnCheck.stories.storyshot
  frontend/src/components/common/__snapshots__/AlertNotification.NoErrorInitially.stories.storyshot
  frontend/src/components/common/__snapshots__/AlertNotification.OnExcludedRoute.stories.storyshot
  frontend/src/components/common/__snapshots__/AlertNotification.OnNonClusterRoute.stories.storyshot
  frontend/src/components/common/__snapshots__/AlertNotification.SimulatingOffline.stories.storyshot
Labels: cncf-cla: yes, approved, size/L

#3541 frontend: ingress: Display missing port for default backend
  frontend/src/components/ingress/Details.tsx
Labels: frontend, cncf-cla: yes, approved, size/XS

#3506 Frontend: PodDetails: Fix wrong verbs
  frontend/src/components/pod/Details.tsx
Labels: cncf-cla: yes, approved, size/M

#3581 github: Add hl-ci- as a branch name prefix
  .github/workflows/pr-to-update-chart.yml
  .github/workflows/pr-to-update-choco.yml
  .github/workflows/pr-to-update-homebrew.yml
  .github/workflows/pr-to-update-minikube.yml
  .github/workflows/pr-to-update-winget.yml
Labels: cncf-cla: yes, approved, size/M

#3568 Use shx
  app/package-lock.json
  app/package.json
  frontend/package-lock.json
  frontend/package.json
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: cncf-cla: yes, size/XL, approved

#3589 frontend: fix two key react warnings
  frontend/src/components/common/Resource/MetadataDisplay.tsx
  frontend/src/components/common/SectionHeader.tsx
Labels: lgtm, cncf-cla: yes, approved, size/XS

#3593 fix the kind at cr creation template
  frontend/src/components/crd/__snapshots__/CustomResourceDefinition.Details.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceList.List.stories.storyshot
  frontend/src/lib/k8s/crd.ts
Labels: lgtm, cncf-cla: yes, approved, size/XS

#3587 frontend: Chart: Fix UI bugs
  frontend/src/components/common/Chart.tsx
Labels: kind/bug, frontend, a11y, charts, lgtm, cncf-cla: yes, approved, size/M

#3602 backend: headlampConfig: move headlampConfig and import in modules
  backend/cmd/headlamp.go
  backend/cmd/headlamp_test.go
  backend/cmd/server.go
  backend/cmd/stateless.go
  backend/cmd/stateless_test.go
  backend/pkg/headlampconfig/headlampConfig.go
Labels: cncf-cla: yes, approved, size/L

#3527 frontend: Map: Various small fixes
  frontend/src/components/App/Layout.tsx
  frontend/src/components/resourceMap/GraphRenderer.tsx
  frontend/src/components/resourceMap/GraphView.css
  frontend/src/components/resourceMap/GraphView.tsx
  frontend/src/components/resourceMap/SelectionBreadcrumbs.tsx
  frontend/src/components/resourceMap/__snapshots__/GraphView.BasicExample.stories.storyshot
  frontend/src/components/resourceMap/details/GraphNodeDetails.tsx
  frontend/src/components/resourceMap/graph/graphLayout.tsx
  frontend/src/components/resourceMap/nodes/GroupNode.tsx
  frontend/src/lib/router.tsx
  frontend/src/setupTests.ts
Labels: lgtm, cncf-cla: yes, size/XL, approved

#3617 backend: Update Helm dependency
  backend/go.mod
  backend/go.sum
Labels: lgtm, cncf-cla: yes, approved, size/L

#3354 frontend: Table: Add Global filter
  frontend/src/components/common/Table/Table.tsx
  frontend/src/components/common/Table/__snapshots__/Table.WithGlobalFilter.stories.storyshot
  frontend/src/components/workload/Overview.tsx
Labels: cncf-cla: yes, approved, size/L

#3613 frontend: BackendTLSPolicy: Add Model, List, Details and Storybook
  frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarClosed.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarOpen.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.SelectedItemWithSidebarOmitted.stories.storyshot
  frontend/src/components/Sidebar/useSidebarItems.ts
  frontend/src/components/gateway/BackendTLSPolicyDetails.tsx
  frontend/src/components/gateway/BackendTLSPolicyList.stories.tsx
  frontend/src/components/gateway/BackendTLSPolicyList.tsx
  frontend/src/components/gateway/BackendTLSPollicyDetails.stories.tsx
  frontend/src/components/gateway/__snapshots__/BackendTLSPolicyList.Items.stories.storyshot
  frontend/src/components/gateway/__snapshots__/BackendTLSPollicyDetails.Basic.stories.storyshot
  frontend/src/components/gateway/storyHelper.ts
  frontend/src/i18n/locales/de/glossary.json
  frontend/src/i18n/locales/en/glossary.json
  frontend/src/i18n/locales/es/glossary.json
  frontend/src/i18n/locales/fr/glossary.json
  frontend/src/i18n/locales/hi/glossary.json
  frontend/src/i18n/locales/it/glossary.json
  frontend/src/i18n/locales/ja/glossary.json
  frontend/src/i18n/locales/ko/glossary.json
  frontend/src/i18n/locales/pt/glossary.json
  frontend/src/i18n/locales/zh-tw/glossary.json
  frontend/src/i18n/locales/zh/glossary.json
  frontend/src/lib/k8s/backendTLSPolicy.ts
  frontend/src/lib/router.tsx
Labels: cncf-cla: yes, approved, size/XXL

#3629 frontend: Add missing entries in translations
  frontend/src/i18n/locales/ta/glossary.json
Labels: cncf-cla: yes, approved, size/XS

#3624 add air file for automatic reload
  .gitignore
  Makefile
  backend/.air.toml
Labels: lgtm, cncf-cla: yes, approved, size/M

#3633 backend: update air.toml file with latest tamplate
  .gitignore
  backend/.air.toml
Labels: lgtm, cncf-cla: yes, approved, size/M

#3635 frontend:fix the overflow taints node table
  frontend/src/components/node/__snapshots__/List.Nodes.stories.storyshot
  frontend/src/components/node/utils.tsx
Labels: lgtm, cncf-cla: yes, approved, size/XS

#3644 added storybook and its storyshots
  frontend/src/components/App/AppLogo.stories.tsx
  frontend/src/components/App/__snapshots__/AppLogo.LargeDark.stories.storyshot
  frontend/src/components/App/__snapshots__/AppLogo.LargeLight.stories.storyshot
  frontend/src/components/App/__snapshots__/AppLogo.SmallDark.stories.storyshot
  frontend/src/components/App/__snapshots__/AppLogo.SmallLight.stories.storyshot
Labels: cncf-cla: yes, approved, size/L

#3650 app: .github: Run tests and type checker plus fix broken things
  .github/workflows/app.yml
  Makefile
  app/README.md
  app/electron/env-paths.ts
  app/electron/main.ts
  app/electron/plugin-management.test.ts
  app/electron/plugin-management.ts
  app/electron/preload.ts
  app/electron/runCmd.ts
  app/electron/windowSize.test.ts
  app/package-lock.json
  app/package.json
  app/tsconfig.json
  docs/development/architecture.md
Labels: cncf-cla: yes, approved, size/L

#3674 fix: update extraManifests example
  charts/headlamp/values.yaml
Labels: cncf-cla: yes, approved, size/XS

#3670 frontend: NodeShellSettings: Add Storybook and its snapshots
  frontend/src/components/App/Settings/NodeShellSettings.stories.tsx
  frontend/src/components/App/Settings/__snapshots__/NodeShellSettings.Default.stories.storyshot
Labels: cncf-cla: yes, approved, size/L

#3652 frontend: Table: Include filter value for memoization
  frontend/src/components/common/Table/Table.tsx
Labels: kind/bug, frontend, cncf-cla: yes, approved, size/XS

#3586 frontend: resourceMap: Unify network icon with sidebar
  frontend/src/components/resourceMap/sources/definitions/sources.tsx
Labels: cncf-cla: yes, approved, size/XS

#3679 charts: Bump Headlamp version to v0.33.0
  charts/headlamp/Chart.yaml
  charts/headlamp/tests/expected_templates/azure-oidc-with-validators.yaml
  charts/headlamp/tests/expected_templates/default.yaml
  charts/headlamp/tests/expected_templates/extra-args.yaml
  charts/headlamp/tests/expected_templates/extra-manifests.yaml
  charts/headlamp/tests/expected_templates/non-azure-oidc.yaml
  charts/headlamp/tests/expected_templates/oidc-create-secret.yaml
  charts/headlamp/tests/expected_templates/oidc-directly-env.yaml
  charts/headlamp/tests/expected_templates/oidc-directly.yaml
  charts/headlamp/tests/expected_templates/oidc-external-secret.yaml
  charts/headlamp/tests/expected_templates/oidc-validator-overrides.yaml
  charts/headlamp/tests/expected_templates/volumes-added.yaml
Labels: cncf-cla: yes, approved, size/L

#3667 frontend:add create resource button for pod and job creation
  frontend/src/components/cronjob/__snapshots__/CronJobDetails.EveryAst.stories.storyshot
  frontend/src/components/cronjob/__snapshots__/CronJobDetails.EveryMinute.stories.storyshot
  frontend/src/components/job/List.tsx
  frontend/src/components/job/__snapshots__/JobList.Items.stories.storyshot
  frontend/src/components/namespace/__snapshots__/NamespaceDetails.Active.stories.storyshot
  frontend/src/components/pod/List.tsx
  frontend/src/components/pod/__snapshots__/PodList.Items.stories.storyshot
  frontend/src/lib/k8s/job.ts
  frontend/src/lib/k8s/pod.ts
Labels: cncf-cla: yes, approved, size/L

#3677 frontend: Update pluginLib test to only check for presense of external libs
  frontend/src/plugin/__snapshots__/pluginLib.snapshot
  frontend/src/plugin/pluginLib.test.ts
Labels: frontend, cncf-cla: yes, approved, size/XXL

#3693 fix the editor close after successfull apply
  frontend/src/components/common/Resource/EditorDialog.tsx
Labels: cncf-cla: yes, approved, size/XS

#3687 Accessibility [FastPass]: Fix contrast for cluster error message text on all themes
  frontend/src/components/cluster/ClusterGroupErrorMessage.tsx
  frontend/src/components/cluster/__snapshots__/ClusterGroupErrorMessage.WithClusterErrors.stories.storyshot
  frontend/src/components/cluster/__snapshots__/ClusterGroupErrorMessage.WithMutipleErrorsPerCluster.stories.storyshot
Labels: kind/bug, a11y, regression, cncf-cla: yes, size/S, approved

#3699 Accessibility [FastPass]: Fix contrast for labels for dark mode
  frontend/src/components/common/Label.tsx
Labels: frontend, a11y, lgtm, cncf-cla: yes, approved, size/XS

#3700 Accessibility [FastPass]: Fix ARIA label and tab navigation for notifications menu
  frontend/src/components/App/Notifications/List/List.tsx
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/hi/translation.json
  frontend/src/i18n/locales/it/translation.json
  frontend/src/i18n/locales/ja/translation.json
  frontend/src/i18n/locales/ko/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/ta/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
  frontend/src/i18n/locales/zh/translation.json
Labels: frontend, a11y, lgtm, cncf-cla: yes, size/S, approved

#3542 Accessibility [FastPass]: Fix settings general missing aria input labels
  frontend/src/components/App/Settings/NumRowsInput.tsx
  frontend/src/components/App/Settings/Settings.tsx
  frontend/src/components/App/Settings/__snapshots__/Settings.General.stories.storyshot
  frontend/src/components/common/NameValueTable/NameValueTable.tsx
  frontend/src/components/common/TimezoneSelect/TimezoneSelect.tsx
Labels: a11y, lgtm, cncf-cla: yes, approved, size/M

#3705 frontend: Link: Pass custom resource definitions to Activities
  frontend/src/components/common/Link.tsx
Labels: lgtm, cncf-cla: yes, approved, size/XS

#3703 frontend: app: headlamp-plugin: Update vulnerable form-data package with audit fix
  app/package-lock.json
  frontend/package-lock.json
  plugins/headlamp-plugin/package-lock.json
Labels: lgtm, cncf-cla: yes, approved, size/L

#3691 frontend: Activity: Fix exit overview mode when last activity is manually closed
  frontend/src/components/activity/Activity.tsx
Labels: kind/bug, cncf-cla: yes, approved, size/XS

#3598 Accessibility [FastPass]: Fix FastPass ARIA checks for cluster page in settings
  frontend/src/components/App/Settings/NodeShellSettings.tsx
  frontend/src/components/App/Settings/SettingsCluster.tsx
  frontend/src/components/App/Settings/__snapshots__/NodeShellSettings.Default.stories.storyshot
Labels: a11y, lgtm, cncf-cla: yes, size/S, approved

#3716 manifest: Update prometheus archive url for v0.7.2
  app/app-build-manifest.json
  container/build-manifest.json
Labels: cncf-cla: yes, approved, size/XS

#3688 frontend: ClusterSelector: Create a separate component for ClusterSel…
  frontend/src/components/App/Settings/ClusterSelector.stories.tsx
  frontend/src/components/App/Settings/ClusterSelector.tsx
  frontend/src/components/App/Settings/SettingsCluster.tsx
  frontend/src/components/App/Settings/__snapshots__/ClusterSelector.Default.stories.storyshot
  frontend/src/components/App/Settings/__snapshots__/ClusterSelector.storyshots.test.tsx.snap
  frontend/src/components/App/Settings/__snapshots__/NodeShellSettings.Default.stories.storyshot
Labels: cncf-cla: yes, approved, size/L

#3612 frontend: Pod: Add tooltip for requests and limits
  frontend/src/components/common/Tooltip/TooltipIcon.tsx
  frontend/src/components/pod/List.tsx
  frontend/src/components/pod/__snapshots__/PodList.Items.stories.storyshot
  frontend/src/i18n/locales/de/glossary.json
  frontend/src/i18n/locales/en/glossary.json
  frontend/src/i18n/locales/es/glossary.json
  frontend/src/i18n/locales/fr/glossary.json
  frontend/src/i18n/locales/hi/glossary.json
  frontend/src/i18n/locales/it/glossary.json
  frontend/src/i18n/locales/ja/glossary.json
  frontend/src/i18n/locales/ko/glossary.json
  frontend/src/i18n/locales/pt/glossary.json
  frontend/src/i18n/locales/ta/glossary.json
  frontend/src/i18n/locales/zh-tw/glossary.json
  frontend/src/i18n/locales/zh/glossary.json
Labels: kind/feature, frontend, cncf-cla: yes, approved, size/L
