Repository kubernetes-sigs/headlamp, pull requests merged in 2025-06, with the labels that each got.

#3374 frontend: Move useTypedSelector to redux/hooks and decouple
  frontend/src/App.tsx
  frontend/src/components/App/AppLogo.tsx
  frontend/src/components/App/CreateCluster/AddCluster.tsx
  frontend/src/components/App/Home/ClusterContextMenu.tsx
  frontend/src/components/App/Layout.tsx
  frontend/src/components/App/Notifications/List/List.tsx
  frontend/src/components/App/Notifications/Notifications.tsx
  frontend/src/components/App/PluginSettings/PluginSettings.tsx
  frontend/src/components/App/PluginSettings/PluginSettingsDetails.tsx
  frontend/src/components/App/RouteSwitcher.tsx
  frontend/src/components/App/Settings/DrawerModeSettings.tsx
  frontend/src/components/App/Settings/Settings.tsx
  frontend/src/components/App/Settings/hook.tsx
  frontend/src/components/App/TopBar.tsx
  frontend/src/components/App/VersionDialog.tsx
  frontend/src/components/DetailsViewSection/DetailsViewSection.tsx
  frontend/src/components/Sidebar/NavigationTabs.tsx
  frontend/src/components/Sidebar/Sidebar.tsx
  frontend/src/components/Sidebar/VersionButton.tsx
  frontend/src/components/Sidebar/useSidebarItems.ts
  frontend/src/components/cluster/Chooser.tsx
  frontend/src/components/cluster/Overview.tsx
  frontend/src/components/common/ActionsNotifier.tsx
  frontend/src/components/common/Link.tsx
  frontend/src/components/common/NamespacesAutocomplete.tsx
  frontend/src/components/common/Resource/DetailsDrawer.tsx
  frontend/src/components/common/Resource/MainInfoSection/MainInfoSectionHeader.tsx
  frontend/src/components/common/Resource/Resource.tsx
  frontend/src/components/common/Resource/ResourceTable.tsx
  frontend/src/components/common/SectionFilterHeader.tsx
  frontend/src/components/globalSearch/GlobalSearchContent.tsx
  frontend/src/components/resourceMap/GraphView.tsx
  frontend/src/components/resourceMap/kubeIcon/KubeIcon.tsx
  frontend/src/lib/k8s/index.ts
  frontend/src/lib/util.ts
  frontend/src/plugin/Plugins.tsx
  frontend/src/redux/hooks.ts
  frontend/src/redux/reducers/reducers.tsx
  frontend/src/redux/uiSlice.ts
Labels: kind/bug, dx, lgtm, cncf-cla: yes, approved, size/M

#3433 ci: Update windows version to windows-2025
  .github/workflows/app.yml
Labels: lgtm, cncf-cla: yes, approved, size/XS

#3431 frontend: AuthChooser: Update buttons for better visibility
  frontend/src/components/authchooser/__snapshots__/AuthChooser.AuthTypeoidc.stories.storyshot
  frontend/src/components/authchooser/__snapshots__/AuthChooser.BasicAuthChooser.stories.storyshot
  frontend/src/components/authchooser/__snapshots__/AuthChooser.HaveClusters.stories.storyshot
  frontend/src/components/authchooser/index.tsx
Labels: kind/bug, frontend, lgtm, cncf-cla: yes, size/S, approved

#3440 app: Bump version to 0.31.1
  app/package-lock.json
  app/package.json
Labels: cncf-cla: yes, approved, size/XS

#3452 docs: update ingress example
  docs/installation/in-cluster/index.md
  kubernetes-headlamp-ingress-sample.yaml
Labels: lgtm, cncf-cla: yes, approved, size/XS

#3457 backend: Update go toolchain to 1.24.4
  backend/go.mod
Labels: backend, security, lgtm, cncf-cla: yes, approved, size/XS

#3389 frontend: Map: Add weights to GraphNodes
  frontend/src/components/resourceMap/graph/graphGrouping.test.ts
  frontend/src/components/resourceMap/graph/graphGrouping.tsx
  frontend/src/components/resourceMap/graph/graphLayout.tsx
  frontend/src/components/resourceMap/graph/graphModel.test.ts
  frontend/src/components/resourceMap/graph/graphModel.tsx
  frontend/src/components/resourceMap/nodes/KubeObjectNode.tsx
Labels: lgtm, cncf-cla: yes, approved, size/L

#3432 frontend: Improve Delete dialog
  frontend/src/components/common/ConfirmDialog.tsx
  frontend/src/components/common/Resource/DeleteButton.tsx
  frontend/src/components/common/__snapshots__/ConfirmDialog.ConfirmDialog.stories.storyshot
  frontend/src/components/common/__snapshots__/ConfirmDialog.ConfirmDialogCancelHidden.stories.storyshot
Labels: frontend, lgtm, cncf-cla: yes, size/S, approved

#3463 Update index.md
  docs/development/index.md
Labels: lgtm, cncf-cla: yes, approved, size/XS

#3477 frontend: Disable websocket multiplexer
  frontend/src/lib/k8s/api/v2/useKubeObjectList.ts
Labels: lgtm, cncf-cla: yes, approved, size/XS

#3480 Add notice about apps not being signed
  docs/installation/desktop/index.mdx
Labels: cncf-cla: yes, size/S, approved

#3459 Add cloud build / push to gcr.io
  Makefile
  cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, do-not-merge/hold, approved, size/M

#3492 frontend: ReferenceGrants: Add Model, List, Details and Storybook
  frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarClosed.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarOpen.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.SelectedItemWithSidebarOmitted.stories.storyshot
  frontend/src/components/Sidebar/useSidebarItems.ts
  frontend/src/components/gateway/ReferenceGrantDetails.stories.tsx
  frontend/src/components/gateway/ReferenceGrantDetails.tsx
  frontend/src/components/gateway/ReferenceGrantList.stories.tsx
  frontend/src/components/gateway/ReferenceGrantList.tsx
  frontend/src/components/gateway/__snapshots__/ReferenceGrantDetails.Basic.stories.storyshot
  frontend/src/components/gateway/__snapshots__/ReferenceGrantList.Items.stories.storyshot
  frontend/src/components/gateway/storyHelper.ts
  frontend/src/i18n/locales/de/glossary.json
  frontend/src/i18n/locales/en/glossary.json
  frontend/src/i18n/locales/es/glossary.json
  frontend/src/i18n/locales/fr/glossary.json
  frontend/src/i18n/locales/hi/glossary.json
  frontend/src/i18n/locales/it/glossary.json
  frontend/src/i18n/locales/ja/glossary.json
  frontend/src/i18n/locales/ko/glossary.json
  frontend/src/i18n/locales/pt/glossary.json
  frontend/src/i18n/locales/zh-tw/glossary.json
  frontend/src/i18n/locales/zh/glossary.json
  frontend/src/lib/k8s/referenceGrant.ts
  frontend/src/lib/router.tsx
Labels: cncf-cla: yes, approved, size/XXL

#3340 frontend: map: Add Custom Resources support
  frontend/src/components/resourceMap/GraphView.tsx
  frontend/src/components/resourceMap/details/GraphNodeDetails.tsx
  frontend/src/components/resourceMap/graph/graphModel.tsx
  frontend/src/components/resourceMap/sources/GraphSources.tsx
  frontend/src/components/resourceMap/sources/GraphSourcesView.tsx
  frontend/src/components/resourceMap/sources/definitions/relations.tsx
  frontend/src/components/resourceMap/sources/definitions/sources.tsx
  frontend/src/lib/k8s/crd.ts
Labels: kind/feature, frontend, lgtm, resourceMap, cncf-cla: yes, approved, size/L, CRD

#3410 Templates: Add a pull request template
  .github/pull_request_template.md
Labels: lgtm, cncf-cla: yes, size/S, approved

#3465 Update headlamp-plugin and charts to use pluginctl package
  charts/headlamp/templates/deployment.yaml
  plugins/headlamp-plugin/README.md
  plugins/headlamp-plugin/bin/headlamp-plugin.js
  plugins/headlamp-plugin/dependencies-sync.js
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
  plugins/headlamp-plugin/plugin-management/multi-plugin-management.js
  plugins/headlamp-plugin/plugin-management/multi-plugin-management.test.js
  plugins/headlamp-plugin/plugin-management/plugin-management.e2e.js
  plugins/headlamp-plugin/plugin-management/plugin-management.js
  plugins/headlamp-plugin/plugin-management/plugin-management.test.js
Labels: cncf-cla: yes, approved, size/XXL

#3387 frontend: i18n: Add missing translations for UI
  frontend/src/components/common/NamespacesAutocomplete.tsx
  frontend/src/i18n/locales/de/glossary.json
  frontend/src/i18n/locales/en/glossary.json
  frontend/src/i18n/locales/es/glossary.json
  frontend/src/i18n/locales/fr/glossary.json
  frontend/src/i18n/locales/hi/glossary.json
  frontend/src/i18n/locales/hi/translation.json
  frontend/src/i18n/locales/it/glossary.json
  frontend/src/i18n/locales/ja/glossary.json
  frontend/src/i18n/locales/ko/glossary.json
  frontend/src/i18n/locales/pt/glossary.json
  frontend/src/i18n/locales/zh-tw/glossary.json
  frontend/src/i18n/locales/zh/glossary.json
Labels: cncf-cla: yes, approved, size/M

#3423 frontend: Add delete cluster button for non dynamic clusters
  backend/cmd/headlamp.go
  backend/pkg/config/config.go
  frontend/src/components/App/Home/ClusterContextMenu.tsx
  frontend/src/components/App/Home/ClusterTable.tsx
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/hi/translation.json
  frontend/src/i18n/locales/it/translation.json
  frontend/src/i18n/locales/ja/translation.json
  frontend/src/i18n/locales/ko/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
  frontend/src/i18n/locales/zh/translation.json
  frontend/src/lib/k8s/api/v1/clusterApi.ts
  frontend/src/stateless/index.ts
Labels: lgtm, cncf-cla: yes, approved, size/L

#3458 tools: Add releaser for helping manage and automate the release process
  tools/releaser/.gitignore
  tools/releaser/package-lock.json
  tools/releaser/package.json
  tools/releaser/src/commands/check.ts
  tools/releaser/src/commands/publish.ts
  tools/releaser/src/commands/start.ts
  tools/releaser/src/commands/tag.ts
  tools/releaser/src/index.ts
  tools/releaser/src/utils/git.ts
  tools/releaser/src/utils/github.ts
  tools/releaser/src/utils/version.ts
  tools/releaser/tsconfig.json
Labels: cncf-cla: yes, approved, size/XXL

#3525 frontend: Ingress: Mark rules field as optional
  frontend/src/components/ingress/Details.tsx
  frontend/src/components/resourceMap/sources/definitions/relations.tsx
  frontend/src/lib/k8s/ingress.ts
Labels: kind/bug, frontend, lgtm, cncf-cla: yes, approved, size/XS

#3534 Makefile: Update frontend-lint-fix command
  Makefile
Labels: quality, lgtm, cncf-cla: yes, approved, size/XS

#3530 chocolatey: Bump Headlamp version to 0.32.0
  app/windows/chocolatey/headlamp.nuspec
  app/windows/chocolatey/tools/chocolateyinstall.ps1
Labels: lgtm, cncf-cla: yes, approved, size/XS

#3535 Add "make lint" and "lint-fix" targets
  Makefile
Labels: lgtm, cncf-cla: yes, approved, size/XS
