Repository kubernetes-sigs/headlamp, pull requests merged in 2025-04, with the labels that each got.

#3066 Add NOTICE file
  NOTICE
Labels: cncf-cla: yes, size/M

#3060 Add notice about the move to README.md
  README.md
Labels: cncf-cla: yes, approved, size/XS

#3073 Add Swisscom as an adopter
  ADOPTERS.md
Labels: lgtm, cncf-cla: yes, approved, size/XS

#3075 Add Millennium bcp to the adopters list
  ADOPTERS.md
Labels: lgtm, cncf-cla: yes, approved, size/XS

#3082 kubernetes-headlamp.yaml: Add readinessProbe to deployment
  kubernetes-headlamp.yaml
Labels: lgtm, cncf-cla: yes, approved, size/XS

#3076 update instruction for headless mode on mac
  docs/installation/desktop/headless.mdx
Labels: lgtm, cncf-cla: yes, approved, size/XS

#3079 docs: Update links to APIs in the plugin functionality page
  docs/development/plugins/functionality/index.md
Labels: lgtm, cncf-cla: yes, approved, size/M

#3089 app, frontend: Unify locales
  app/electron/i18n-helper.ts
  app/electron/i18next-parser.config.js
  app/package-lock.json
  app/package.json
  docs/development/i18n/contributing.md
  frontend/src/i18n/config.ts
  frontend/src/i18n/i18next-parser.config.js
  frontend/src/i18n/i18nextSharedConfig.mjs
  frontend/src/i18n/locales/de/app.json
  frontend/src/i18n/locales/en/app.json
  frontend/src/i18n/locales/es/app.json
  frontend/src/i18n/locales/fr/app.json
  frontend/src/i18n/locales/it/app.json
  frontend/src/i18n/locales/pt/app.json
  frontend/src/i18n/locales/zh-tw/app.json
Labels: lgtm, cncf-cla: yes, approved, size/L

#3095 eslint: documentaton: fix dead link to headlamp eslint-config
  eslint-config/package.json
Labels: lgtm, cncf-cla: yes, approved, size/XS

#3097 backend: fix helm repo test
  backend/pkg/helm/repository_test.go
Labels: cncf-cla: yes, approved, size/XS

#3013 multiplexer: Fix token refresh for ws reconnection
  backend/cmd/multiplexer.go
  backend/cmd/multiplexer_test.go
  frontend/src/lib/k8s/api/v2/webSocket.test.ts
  frontend/src/lib/k8s/api/v2/webSocket.ts
Labels: backend, frontend, size:L, lgtm, multi, cncf-cla: yes, approved, size/L

#3072 github: backend: charts: Fix repo link
  .github/workflows/app-artifacts-win.yml
  README.md
  backend/cmd/headlamp.go
  backend/cmd/headlamp_test.go
  backend/cmd/multiplexer.go
  backend/cmd/multiplexer_test.go
  backend/cmd/server.go
  backend/cmd/stateless.go
  backend/cmd/stateless_test.go
  backend/go.mod
  backend/pkg/cache/cache_test.go
  backend/pkg/config/config.go
  backend/pkg/config/config_test.go
  backend/pkg/helm/charts_test.go
  backend/pkg/helm/handler.go
  backend/pkg/helm/release.go
  backend/pkg/helm/release_test.go
  backend/pkg/helm/repository.go
  backend/pkg/helm/repository_test.go
  backend/pkg/kubeconfig/contextStore.go
  backend/pkg/kubeconfig/contextStore_test.go
  backend/pkg/kubeconfig/file_test.go
  backend/pkg/kubeconfig/kubeconfig.go
  backend/pkg/kubeconfig/kubeconfig_test.go
  backend/pkg/kubeconfig/watcher.go
  backend/pkg/kubeconfig/watcher_test.go
  backend/pkg/logger/logger_test.go
  backend/pkg/plugins/plugins.go
  backend/pkg/plugins/plugins_test.go
  backend/pkg/portforward/handler.go
  backend/pkg/portforward/handler_test.go
  backend/pkg/portforward/internal_test.go
  backend/pkg/portforward/store.go
  backend/pkg/utils/utils_test.go
  charts/headlamp/Chart.yaml
  docker-extension/Dockerfile
Labels: cncf-cla: yes, approved, size/L

#3104 github/backend-test: Fix coverage so it skips when main fails
  .github/workflows/backend-test.yml
Labels: cncf-cla: yes, size/S, approved

#3044 github/workflows/push-release-assets: Fix pushing assets
  .github/workflows/push-release-assets.yml
  app/scripts/push-release-assets/push-release-assets.js
Labels: size:XS, cncf-cla: yes, approved, size/XS

#3081 frontend: plugins: Bump vite to 6.2.5
  frontend/package-lock.json
  plugins/examples/app-menus/package-lock.json
  plugins/examples/change-logo/package-lock.json
  plugins/examples/cluster-chooser/package-lock.json
  plugins/examples/customizing-map/package-lock.json
  plugins/examples/details-view/package-lock.json
  plugins/examples/dynamic-clusters/package-lock.json
  plugins/examples/headlamp-events/package-lock.json
  plugins/examples/pod-counter/package-lock.json
  plugins/examples/resource-charts/package-lock.json
  plugins/examples/sidebar/package-lock.json
  plugins/examples/tables/package-lock.json
  plugins/headlamp-plugin/package-lock.json
Labels: cncf-cla: yes, approved, size/M

#3090 frontend: Add option to alphabetize sidebar items
  frontend/src/components/App/Settings/Settings.tsx
  frontend/src/components/App/Settings/__snapshots__/Settings.General.stories.storyshot
  frontend/src/components/Sidebar/useSidebarItems.ts
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/it/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
  frontend/src/redux/configSlice.ts
Labels: cncf-cla: yes, approved, size/M

#3113 frontend: plugins: Bump vite to 6.2.6
  frontend/package-lock.json
  plugins/examples/app-menus/package-lock.json
  plugins/examples/change-logo/package-lock.json
  plugins/examples/cluster-chooser/package-lock.json
  plugins/examples/customizing-map/package-lock.json
  plugins/examples/details-view/package-lock.json
  plugins/examples/dynamic-clusters/package-lock.json
  plugins/examples/headlamp-events/package-lock.json
  plugins/examples/pod-counter/package-lock.json
  plugins/examples/resource-charts/package-lock.json
  plugins/examples/sidebar/package-lock.json
  plugins/examples/tables/package-lock.json
  plugins/headlamp-plugin/package-lock.json
Labels: dependencies, cncf-cla: yes, approved, size/M

#3125 frontend: Sidebar: Use theme color for Add Cluster Button
  frontend/src/components/Sidebar/Sidebar.tsx
Labels: frontend, cncf-cla: yes, approved, size/XS

#3127 backend: fix some typo errors
  backend/cmd/headlamp.go
  backend/cmd/stateless.go
  backend/pkg/kubeconfig/contextStore.go
Labels: cncf-cla: yes, approved, size/XS

#3138 frontend: Map: Persist query params on refresh
  frontend/src/components/resourceMap/GraphView.tsx
Labels: resourceMap, cncf-cla: yes, size/S, approved

#3130 frontend: pod: Add quick status for containers
  frontend/src/components/pod/Details.tsx
  frontend/src/components/pod/List.tsx
  frontend/src/components/pod/__snapshots__/PodDetails.Error.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.Initializing.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.LivenessFailed.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.PullBackOff.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.Running.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.Successful.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodList.Items.stories.storyshot
Labels: kind/feature, frontend, cncf-cla: yes, approved, size/L

#3140 backend: Bump helm and golang dependencies
  backend/go.mod
  backend/go.sum
Labels: dependencies, cncf-cla: yes, approved, size/L

#3134 frontend: truncate long cronjob names
  frontend/src/components/cronjob/Details.tsx
Labels: cncf-cla: yes, approved, size/XS

#3118 frontend: Update sidebar when locale changes
  frontend/src/components/Sidebar/useSidebarItems.ts
Labels: i18n, lgtm, cncf-cla: yes, approved, size/XS

#3128 backend: add support for skip context
  backend/cmd/headlamp.go
  backend/cmd/headlamp_test.go
  backend/cmd/server.go
  backend/pkg/config/config.go
  backend/pkg/kubeconfig/kubeconfig.go
  backend/pkg/kubeconfig/kubeconfig_test.go
  backend/pkg/kubeconfig/watcher.go
  backend/pkg/kubeconfig/watcher_test.go
Labels: cncf-cla: yes, approved, size/M

#3098 frontend: Add simplified Theme preview to Settings and Search
  frontend/src/components/App/Settings/Settings.tsx
  frontend/src/components/App/Settings/ThemePreview.tsx
  frontend/src/components/App/Settings/__snapshots__/Settings.General.stories.storyshot
  frontend/src/components/globalSearch/GlobalSearchContent.tsx
Labels: cncf-cla: yes, approved, size/L

#3126 Review Japanese Translations
  frontend/src/components/common/Table/Table.tsx
  frontend/src/i18n/ThemeProviderNexti18n.tsx
  frontend/src/i18n/config.ts
  frontend/src/i18n/locales/ja/app.json
  frontend/src/i18n/locales/ja/glossary.json
  frontend/src/i18n/locales/ja/translation.json
Labels: cncf-cla: yes, approved, size/L

#3091 Add japanese locale and owner
  frontend/src/components/common/Table/Table.tsx
  frontend/src/i18n/ThemeProviderNexti18n.tsx
  frontend/src/i18n/config.ts
  frontend/src/i18n/locales/ja/app.json
  frontend/src/i18n/locales/ja/glossary.json
  frontend/src/i18n/locales/ja/translation.json
Labels: lgtm, cncf-cla: yes, size/XL, approved

#3147 docs: Fix links refs
  docs/development/plugins/how-to.md
Labels: cncf-cla: yes, approved, size/XS

#3119 frontend: Home: Add multi cluster selection
  e2e-tests/tests/multiCluster.spec.ts
  frontend/src/components/App/Home/ClusterContextMenu.tsx
  frontend/src/components/App/Home/ClusterTable.tsx
  frontend/src/components/App/Home/RecentClusters.tsx
  frontend/src/components/App/Home/__snapshots__/RecentClusters.MoreThanThreeClusters.stories.storyshot
  frontend/src/components/App/Home/__snapshots__/RecentClusters.OneRecentCluster.stories.storyshot
  frontend/src/components/App/Home/__snapshots__/RecentClusters.ThreeClusters.stories.storyshot
  frontend/src/components/App/Home/__snapshots__/RecentClusters.TwoExistingClusters.stories.storyshot
  frontend/src/components/App/Home/__snapshots__/RecentClusters.TwoRecentClusters.stories.storyshot
  frontend/src/components/App/Home/__snapshots__/RecentClusters.WithObsoleteClusters.stories.storyshot
  frontend/src/components/App/Home/config.ts
  frontend/src/components/App/Home/customClusterNames.ts
  frontend/src/components/App/Home/index.tsx
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/it/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
Labels: kind/feature, frontend, multi, cncf-cla: yes, approved, size/XXL

#3142 Improve WebSocket compatibility
  backend/cmd/headlamp.go
  backend/cmd/headlamp_test.go
  backend/cmd/multiplexer.go
Labels: kind/bug, backend, blocker, cncf-cla: yes, approved, size/L

#3141 frontend: Include pod status in column text value to avoid stale status label state
  frontend/src/components/pod/List.tsx
Labels: cncf-cla: yes, size/S, approved

#3153 plugins/examples/dynamic-clusters: Use theme color for buttons
  plugins/examples/dynamic-clusters/src/index.tsx
Labels: plugins, lgtm, cncf-cla: yes, approved, size/XS

#3093 Add registerAppTheme function for plugins
  docs/development/plugins/functionality/images/settings-theme-dropdown.png
  docs/development/plugins/functionality/index.md
  frontend/src/components/App/themeSlice.ts
  frontend/src/plugin/__snapshots__/pluginLib.snapshot
  frontend/src/plugin/index.ts
  frontend/src/plugin/registry.tsx
  frontend/tsconfig.json
  plugins/README.md
  plugins/examples/custom-theme/.gitignore
  plugins/examples/custom-theme/.vscode/extensions.json
  plugins/examples/custom-theme/.vscode/settings.json
  plugins/examples/custom-theme/.vscode/tasks.json
  plugins/examples/custom-theme/README.md
  plugins/examples/custom-theme/package-lock.json
  plugins/examples/custom-theme/package.json
  plugins/examples/custom-theme/src/headlamp-plugin.d.ts
  plugins/examples/custom-theme/src/index.tsx
  plugins/examples/custom-theme/tsconfig.json
Labels: cncf-cla: yes, approved, size/XXL

#3146 frontend: add zh for i18n
  frontend/src/i18n/config.ts
  frontend/src/i18n/locales/zh/app.json
  frontend/src/i18n/locales/zh/glossary.json
  frontend/src/i18n/locales/zh/translation.json
Labels: lgtm, cncf-cla: yes, size/XL, approved

#3144 Fix e2e auth logic + add namespace a11y playwright tests
  e2e-tests/package-lock.json
  e2e-tests/package.json
  e2e-tests/tests/headlampPage.ts
  e2e-tests/tests/namespaces.spec.ts
  frontend/src/components/App/TopBar.tsx
  frontend/src/components/App/__snapshots__/TopBar.OneCluster.stories.storyshot
  frontend/src/components/App/__snapshots__/TopBar.TwoCluster.stories.storyshot
  frontend/src/components/common/CreateResourceButton.tsx
Labels: a11y, e2e-tests, cncf-cla: yes, approved, size/M

#3160 app: backend: Add flag for watching plugins changes
  app/electron/main.ts
  backend/cmd/headlamp.go
  backend/cmd/server.go
  backend/pkg/config/config.go
  docs/development/index.md
Labels: backend, app, cncf-cla: yes, size/S, approved

#3169 Revert "Fix e2e auth logic + add namespace a11y playwright tests"
  e2e-tests/package-lock.json
  e2e-tests/package.json
  e2e-tests/tests/headlampPage.ts
  e2e-tests/tests/namespaces.spec.ts
  frontend/src/components/App/TopBar.tsx
  frontend/src/components/App/__snapshots__/TopBar.OneCluster.stories.storyshot
  frontend/src/components/App/__snapshots__/TopBar.TwoCluster.stories.storyshot
  frontend/src/components/common/CreateResourceButton.tsx
Labels: cncf-cla: yes, approved, size/M

#3173 e2e: Add a11y test for namespace and add aria label to create resourc…
  e2e-tests/package-lock.json
  e2e-tests/package.json
  e2e-tests/tests/namespaces.spec.ts
  frontend/src/components/common/CreateResourceButton.tsx
Labels: cncf-cla: yes, approved, size/M

#3174 backend: Resolve issues with websocket token encoding
  backend/cmd/headlamp.go
  backend/cmd/headlamp_test.go
Labels: kind/bug, backend, regression, AKS, cncf-cla: yes, size/S, approved

#3154 frontend: Table: Add horizontal scrollbar on overflow
  frontend/src/components/App/PluginSettings/__snapshots__/PluginSettings.DefaultSaveEnable.stories.storyshot
  frontend/src/components/App/PluginSettings/__snapshots__/PluginSettings.EmptyHomepageItems.stories.storyshot
  frontend/src/components/App/PluginSettings/__snapshots__/PluginSettings.FewItems.stories.storyshot
  frontend/src/components/App/PluginSettings/__snapshots__/PluginSettings.ManyItems.stories.storyshot
  frontend/src/components/App/PluginSettings/__snapshots__/PluginSettings.MoreItems.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/ResourceListView.OneHiddenColumn.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/ResourceTable.NameSearch.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/ResourceTable.NoFilter.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/ResourceTable.WithHiddenCols.stories.storyshot
  frontend/src/components/common/Table/Table.tsx
  frontend/src/components/common/Table/__snapshots__/Table.Datum.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.Getter.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.LabelSearch.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.NameSearch.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.NamespaceSearch.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.NamespaceSelect.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.NotFoundMessage.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.NumberSearch.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.ReflectInURL.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.ReflectInURLWithPrefix.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.UIDSearch.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.WithFilterMultiSelect.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.WithGlobalFilter.stories.storyshot
  frontend/src/components/common/Table/__snapshots__/Table.WithSorting.stories.storyshot
  frontend/src/components/configmap/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceDefinition.Details.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceDefinition.List.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceList.List.stories.storyshot
  frontend/src/components/cronjob/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/daemonset/__snapshots__/List.DaemonSets.stories.storyshot
  frontend/src/components/deployments/__snapshots__/List.Deployments.stories.storyshot
  frontend/src/components/endpoints/__snapshots__/EndpointList.Items.stories.storyshot
  frontend/src/components/gateway/__snapshots__/ClassList.Items.stories.storyshot
  frontend/src/components/gateway/__snapshots__/GRPCRouteList.Items.stories.storyshot
  frontend/src/components/gateway/__snapshots__/GatewayList.Items.stories.storyshot
  frontend/src/components/gateway/__snapshots__/HTTPRouteList.Items.stories.storyshot
  frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPAList.Items.stories.storyshot
  frontend/src/components/ingress/__snapshots__/ClassList.Items.stories.storyshot
  frontend/src/components/ingress/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/job/__snapshots__/JobList.Items.stories.storyshot
  frontend/src/components/lease/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/limitRange/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/namespace/__snapshots__/NamespaceList.Regular.stories.storyshot
  frontend/src/components/node/__snapshots__/List.Nodes.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodList.Items.stories.storyshot
  frontend/src/components/podDisruptionBudget/__snapshots__/pdbList.Items.stories.storyshot
  frontend/src/components/priorityClass/__snapshots__/priorityClassList.Items.stories.storyshot
  frontend/src/components/replicaset/__snapshots__/List.ReplicaSets.stories.storyshot
  frontend/src/components/resourceQuota/__snapshots__/resourceQuotaList.Items.stories.storyshot
  frontend/src/components/runtimeClass/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/secret/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/ClaimList.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/ClassList.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/VolumeList.Items.stories.storyshot
  frontend/src/components/verticalPodAutoscaler/__snapshots__/VPAList.List.stories.storyshot
  frontend/src/components/webhookconfiguration/__snapshots__/MutatingWebhookConfigList.Items.stories.storyshot
  frontend/src/components/webhookconfiguration/__snapshots__/ValidatingWebhookConfigList.Items.stories.storyshot
Labels: kind/bug, frontend, a11y, regression, cncf-cla: yes, approved, size/L

#3161 plugins/examples/custom-theme: Bump vite to 6.2.6
  plugins/examples/custom-theme/package-lock.json
Labels: dependencies, security, cncf-cla: yes, approved, size/XS

#2990 docs: Add guidance for probe modifications in baser-url
  docs/installation/base-url.md
Labels: size:S, cncf-cla: yes, size/S, approved

#3178 frontend: Fix container status color
  frontend/src/components/pod/List.tsx
Labels: cncf-cla: yes, approved, size/XS

#3176 github/workflows/push-release-assets: Limit token permissions
  .github/workflows/push-release-assets.yml
Labels: security, CI, cncf-cla: yes, approved, size/XS

#3131 app: frontend: plugins: Modify exec and run commands
  app/windows/codesign.js
  frontend/src/make-env.test.js
  plugins/headlamp-plugin/bin/headlamp-plugin.js
  plugins/headlamp-plugin/test-headlamp-plugin.js
Labels: kind/bug, frontend, security, plugins, app, lgtm, cncf-cla: yes, approved, size/M

#3184 i18n: Add Korean locale
  frontend/src/components/common/Table/Table.tsx
  frontend/src/i18n/ThemeProviderNexti18n.tsx
  frontend/src/i18n/config.ts
  frontend/src/i18n/locales/ko/app.json
  frontend/src/i18n/locales/ko/glossary.json
  frontend/src/i18n/locales/ko/translation.json
Labels: cncf-cla: yes, size/XL, approved

#3188 Add Japanese locale and owner (merge into main now)
  frontend/src/components/common/Table/Table.tsx
  frontend/src/i18n/ThemeProviderNexti18n.tsx
  frontend/src/i18n/config.ts
  frontend/src/i18n/locales/ja/app.json
  frontend/src/i18n/locales/ja/glossary.json
  frontend/src/i18n/locales/ja/translation.json
Labels: frontend, app, Table, i18n, lgtm, cncf-cla: yes, size/XL, approved

#3186 frontend: i18n: Table: Add missing locale mappings
  frontend/src/components/common/Table/Table.tsx
  frontend/src/i18n/ThemeProviderNexti18n.tsx
Labels: kind/bug, Table, i18n, cncf-cla: yes, approved, size/M

#3132 frontend: Allow direct editing of resource fields
  frontend/src/components/common/Resource/Resource.tsx
  frontend/src/components/configmap/Details.tsx
  frontend/src/components/configmap/__snapshots__/Details.WithBase.stories.storyshot
  frontend/src/components/secret/Details.tsx
  frontend/src/components/secret/__snapshots__/Details.WithBase.stories.storyshot
Labels: kind/feature, frontend, cncf-cla: yes, approved, size/L

#3190 e2e-tests: Add a11y check with Axe in many tests
  e2e-tests/tests/headlamp.spec.ts
  e2e-tests/tests/headlampPage.ts
  e2e-tests/tests/namespaces.spec.ts
  e2e-tests/tests/namespacesPage.ts
  e2e-tests/tests/pluginSetting.spec.ts
  e2e-tests/tests/podsPage.ts
Labels: frontend, a11y, e2e-tests, cncf-cla: yes, approved, size/M
