Repository kubernetes-sigs/headlamp, pull requests merged in 2025-09, with the labels that each got.

#3843 frontend: improve filter table
  frontend/src/components/common/Resource/ResourceTable.tsx
  frontend/src/components/common/Table/Table.tsx
  frontend/src/components/job/List.tsx
  frontend/src/components/job/__snapshots__/JobList.Items.stories.storyshot
  frontend/src/components/pod/List.tsx
  frontend/src/components/storage/VolumeList.tsx
Labels: lgtm, cncf-cla: yes, approved, size/M

#3835 Add support for i18n in plugins
  docs/development/plugins/i18n.md
  docs/development/plugins/index.md
  frontend/src/plugin/__snapshots__/pluginLib.snapshot
  frontend/src/plugin/index.ts
  frontend/src/plugin/pluginI18n.ts
  plugins/headlamp-plugin/bin/headlamp-plugin.js
  plugins/headlamp-plugin/config/i18next-parser.config.js
  plugins/headlamp-plugin/config/vite-plugin-name-injection.mjs
  plugins/headlamp-plugin/config/vite.config.mjs
  plugins/headlamp-plugin/src/index.ts
  plugins/headlamp-plugin/template/package.json
  plugins/headlamp-plugin/template/src/index.tsx
Labels: cncf-cla: yes, approved, size/XXL

#3740 backend: caching: refactored PR for cache implementation
  backend/cmd/headlamp.go
  backend/cmd/headlamp_test.go
  backend/cmd/server.go
  backend/pkg/config/config.go
  backend/pkg/headlampconfig/headlampConfig.go
  backend/pkg/k8cache/authErrResp.go
  backend/pkg/k8cache/authErrResp_test.go
  backend/pkg/k8cache/authorization.go
  backend/pkg/k8cache/authorization_test.go
  backend/pkg/k8cache/cacheInvalidation.go
  backend/pkg/k8cache/cacheInvalidation_test.go
  backend/pkg/k8cache/cacheStore.go
  backend/pkg/k8cache/cacheStore_test.go
  backend/pkg/k8cache/key.go
  backend/pkg/k8cache/responseCapture.go
  backend/pkg/k8cache/responseCapture_test.go
Labels: cncf-cla: yes, approved, size/XXL

#3818 Make monaco-editor work in an offline/air-gapped environment and fix localisation
  frontend/package-lock.json
  frontend/package.json
  frontend/rsbuild.config.ts
  frontend/src/components/App/AppContainer.tsx
  frontend/src/components/common/Resource/EditorDialog.tsx
  frontend/src/components/monaco/MonacoEditorLoaderInitializer.tsx
  frontend/vite.config.ts
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: kind/bug, security, a11y, regression, cncf-cla: yes, approved, size/L

#3847 frontend: PluginSettingsDetails: Move useDispatch outside delete handler
  frontend/src/components/App/PluginSettings/PluginSettingsDetails.tsx
Labels: frontend, plugins, cncf-cla: yes, approved, kind/regression, size/XS

#3852 CHORE: Update Dockerfile for improved readability and consistency
  Dockerfile
Labels: cncf-cla: yes, size/S, approved

#3853 frontend: Dockerfile: Bump Node.js image version to 22
  Dockerfile
Labels: cncf-cla: yes, approved, size/XS

#3866 chocolatey: Bump Headlamp version to 0.35.0
  app/windows/chocolatey/headlamp.nuspec
  app/windows/chocolatey/tools/chocolateyinstall.ps1
Labels: cncf-cla: yes, approved, size/XS

#3869 charts: Bump Headlamp version to v0.35.0
  charts/headlamp/Chart.yaml
  charts/headlamp/tests/expected_templates/azure-oidc-with-validators.yaml
  charts/headlamp/tests/expected_templates/default.yaml
  charts/headlamp/tests/expected_templates/extra-args.yaml
  charts/headlamp/tests/expected_templates/extra-manifests.yaml
  charts/headlamp/tests/expected_templates/non-azure-oidc.yaml
  charts/headlamp/tests/expected_templates/oidc-create-secret.yaml
  charts/headlamp/tests/expected_templates/oidc-directly-env.yaml
  charts/headlamp/tests/expected_templates/oidc-directly.yaml
  charts/headlamp/tests/expected_templates/oidc-external-secret.yaml
  charts/headlamp/tests/expected_templates/oidc-validator-overrides.yaml
  charts/headlamp/tests/expected_templates/volumes-added.yaml
Labels: cncf-cla: yes, approved, size/L

#3874 frontend: stateless: Extract functions to new files
  frontend/src/components/App/Settings/SettingsCluster.tsx
  frontend/src/lib/k8s/api/v1/clusterApi.ts
  frontend/src/lib/k8s/api/v1/clusterRequests.ts
  frontend/src/lib/k8s/api/v1/portForward.ts
  frontend/src/lib/k8s/api/v1/streamingApi.ts
  frontend/src/lib/k8s/api/v2/fetch.test.ts
  frontend/src/lib/k8s/api/v2/fetch.ts
  frontend/src/lib/k8s/api/v2/webSocket.test.ts
  frontend/src/lib/k8s/api/v2/webSocket.ts
  frontend/src/stateless/findKubeconfigByClusterName.ts
  frontend/src/stateless/getUserIdFromLocalStorage.ts
  frontend/src/stateless/index.ts
Labels: frontend, k8s, cncf-cla: yes, approved, size/L

#3873 frontend: lib/k8s: Fixing some circular imports
  frontend/src/lib/k8s/KubeMetadata.ts
  frontend/src/lib/k8s/api/v1/apply.ts
  frontend/src/lib/k8s/api/v1/clusterApi.ts
  frontend/src/lib/k8s/api/v1/clusterRequests.ts
  frontend/src/lib/k8s/api/v1/factories.ts
  frontend/src/lib/k8s/api/v1/formatUrl.ts
  frontend/src/lib/k8s/api/v1/metricsApi.ts
  frontend/src/lib/k8s/api/v1/scaleApi.ts
  frontend/src/lib/k8s/api/v1/streamingApi.ts
  frontend/src/lib/k8s/api/v2/apiDiscovery.tsx
  frontend/src/lib/k8s/api/v2/useKubeObjectList.ts
Labels: cncf-cla: yes, approved, size/M

#3865 Docs: Fix broken link to architecture from Plugins page
  docs/development/plugins/index.md
Labels: documentation, cncf-cla: yes, approved, size/XS

#3876 frontend: router: Untangling imports
  frontend/src/components/App/CreateCluster/AddCluster.tsx
  frontend/src/components/App/Home/ClusterContextMenu.tsx
  frontend/src/components/App/Home/RecentClusters.tsx
  frontend/src/components/App/Home/index.tsx
  frontend/src/components/App/Notifications/Notifications.tsx
  frontend/src/components/App/RouteSwitcher.stories.tsx
  frontend/src/components/App/RouteSwitcher.tsx
  frontend/src/components/App/Settings/SettingsButton.tsx
  frontend/src/components/App/TopBar.tsx
  frontend/src/components/Sidebar/NavigationTabs.tsx
  frontend/src/components/Sidebar/Sidebar.tsx
  frontend/src/components/Sidebar/SidebarItem.tsx
  frontend/src/components/Sidebar/useSidebarItems.ts
  frontend/src/components/authchooser/index.tsx
  frontend/src/components/cluster/Chooser.tsx
  frontend/src/components/cluster/ClusterChooserPopup.tsx
  frontend/src/components/common/AlertNotification.tsx
  frontend/src/components/common/Link.tsx
  frontend/src/components/common/Resource/MainInfoSection/MainInfoSection.tsx
  frontend/src/components/common/Resource/Resource.tsx
  frontend/src/components/globalSearch/GlobalSearchContent.tsx
  frontend/src/components/project/NewProjectPopup.tsx
  frontend/src/components/project/ProjectCreateFromYaml.tsx
  frontend/src/lib/k8s/KubeObject.ts
  frontend/src/lib/k8s/index.test.ts
  frontend/src/lib/router/Route.tsx
  frontend/src/lib/router/createRouteURL.tsx
  frontend/src/lib/router/getDefaultRoutes.tsx
  frontend/src/lib/router/getRoute.tsx
  frontend/src/lib/router/getRoutePath.tsx
  frontend/src/lib/router/getRouteUseClusterURL.tsx
  frontend/src/lib/router/index.tsx
  frontend/src/plugin/registry.tsx
  frontend/src/redux/routesSlice.test.tsx
  frontend/src/redux/routesSlice.ts
Labels: cncf-cla: yes, size/XL, approved

#3863 app: Update dependencies
  app/package-lock.json
  app/package.json
Labels: dependencies, security, app, cncf-cla: yes, size/XL, approved

#3871 charts: add ability to specify podLabels
  charts/headlamp/README.md
  charts/headlamp/templates/deployment.yaml
  charts/headlamp/values.yaml
Labels: cncf-cla: yes, approved, size/XS

#3747 frontend: Notifications: Fix contrast for menu items on all themes
  frontend/src/components/App/Notifications/List/List.tsx
Labels: a11y, cncf-cla: yes, size/S, approved

#3881 frontend: Add stories for DateLabel
  frontend/src/components/common/Label.stories/DateLabel.stories.tsx
  frontend/src/components/common/Label.stories/__snapshots__/DateLabel.Default.stories.storyshot
  frontend/src/components/common/Label.stories/__snapshots__/DateLabel.MiniLabel.stories.storyshot
Labels: frontend, testing, cncf-cla: yes, approved, size/M, storybook

#3885 frontend: Add snackbars for deleting plugins
  frontend/src/components/App/PluginSettings/PluginSettingsDetails.tsx
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/hi/translation.json
  frontend/src/i18n/locales/it/translation.json
  frontend/src/i18n/locales/ja/translation.json
  frontend/src/i18n/locales/ko/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/ta/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
  frontend/src/i18n/locales/zh/translation.json
  frontend/src/lib/k8s/api/v1/pluginsApi.ts
Labels: frontend, plugins, Notifications, quality, cncf-cla: yes, approved, size/L

#3891 backend: auth: Extract CacheRefreshedToken from headlamp.go
  backend/cmd/headlamp.go
  backend/pkg/auth/auth.go
  backend/pkg/auth/auth_test.go
Labels: backend, auth, quality, cncf-cla: yes, approved, size/L

#3862 [helm] add optional PodDisruptionBudget
  .github/workflows/helm-chart-template-test.yml
  charts/headlamp/README.md
  charts/headlamp/templates/pdb.yaml
  charts/headlamp/tests/expected_templates/pod-disruption.yaml
  charts/headlamp/tests/test_cases/pod-disruption.yaml
  charts/headlamp/values.schema.json
  charts/headlamp/values.yaml
Labels: kind/feature, charts, cncf-cla: yes, approved, size/L

#3904 plugins/examples: Bump headlamp-plugin 0.13.0-alpha.7
  plugins/examples/change-logo/package-lock.json
  plugins/examples/change-logo/package.json
  plugins/examples/cluster-chooser/package-lock.json
  plugins/examples/cluster-chooser/package.json
  plugins/examples/custom-theme/package-lock.json
  plugins/examples/custom-theme/package.json
  plugins/examples/custom-theme/src/headlamp-plugin.d.ts
  plugins/examples/customizing-map/package-lock.json
  plugins/examples/customizing-map/package.json
  plugins/examples/details-view/package-lock.json
  plugins/examples/details-view/package.json
  plugins/examples/details-view/src/index.tsx
  plugins/examples/headlamp-events/package-lock.json
  plugins/examples/headlamp-events/package.json
  plugins/examples/pod-counter/package-lock.json
  plugins/examples/pod-counter/package.json
  plugins/examples/pod-counter/src/Message.stories.tsx
  plugins/examples/pod-counter/src/index.tsx
  plugins/examples/resource-charts/package-lock.json
  plugins/examples/resource-charts/package.json
  plugins/examples/sidebar/package-lock.json
  plugins/examples/sidebar/package.json
  plugins/examples/tables/package-lock.json
  plugins/examples/tables/package.json
  plugins/examples/tables/src/index.tsx
  plugins/examples/ui-panels/package-lock.json
  plugins/examples/ui-panels/package.json
Labels: kind/feature, plugins, headlamp-plugin, cncf-cla: yes, approved, size/XXL

#3901 headlamp-plugin: Fix npm start to log where files are copied
  plugins/headlamp-plugin/bin/headlamp-plugin.js
Labels: kind/bug, regression, headlamp-plugin, cncf-cla: yes, approved

#3905 plugins/examples/app-menus: Bump headlamp-plugin 0.13.0-alpha.7
  plugins/examples/app-menus/package-lock.json
  plugins/examples/app-menus/package.json
  plugins/examples/app-menus/src/index.tsx
Labels: cncf-cla: yes, approved, size/XXL

#3906 headlamp-plugin: Export missing functions
  frontend/src/plugin/registry.tsx
  plugins/headlamp-plugin/src/index.ts
Labels: kind/bug, plugins, headlamp-plugin, lgtm, cncf-cla: yes, size/S, approved

#3922 github: docker-extension-release: Fix to just use latest tag
  .github/workflows/docker-extension-release.yml
Labels: cncf-cla: yes, size/S, approved

#3908 frontend: ResourceTable: Update header translation from 'Type' to 'Kind'
  frontend/src/components/advancedSearch/__snapshots__/ResourceSearch.Default.stories.storyshot
  frontend/src/components/common/Resource/ResourceTable.tsx
  frontend/src/components/workload/__snapshots__/Overview.Workloads.stories.storyshot
Labels: cncf-cla: yes, size/S, approved

#3914 detailsViewSectionSlice: HeaderActionFuncType: Fix return type to contain ReactNode
  frontend/src/components/DetailsViewSection/detailsViewSectionSlice.ts
Labels: kind/bug, plugins, headlamp-plugin, cncf-cla: yes, approved, size/XS

#3889 Feature: now sidebar can have external urls
  frontend/src/components/Sidebar/ListItemLink.tsx
  frontend/src/components/Sidebar/SidebarItem.tsx
  frontend/src/components/Sidebar/__snapshots__/ListItemLink.NoIcon.stories.storyshot
Labels: kind/feature, frontend, lgtm, cncf-cla: yes, approved, size/M, Sidebar

#3935 frontend: Allow overriding default tabs in the project view
  frontend/src/components/project/ProjectDetails.tsx
  frontend/src/redux/projectsSlice.ts
  plugins/examples/projects/README.md
  plugins/examples/projects/src/index.tsx
Labels: plugins, lgtm, cncf-cla: yes, size/XL, approved, projects

#3936 frontend: make naming behavior equal on all resources
  frontend/src/components/endpointSlices/Details.tsx
  frontend/src/components/endpointSlices/__snapshots__/EndpointSliceDetails.Default.stories.storyshot
  frontend/src/components/endpointSlices/__snapshots__/EndpointSliceDetails.Error.stories.storyshot
  frontend/src/components/endpoints/Details.tsx
  frontend/src/components/endpoints/__snapshots__/EndpointDetails.Default.stories.storyshot
  frontend/src/components/endpoints/__snapshots__/EndpointDetails.Error.stories.storyshot
  frontend/src/i18n/locales/de/glossary.json
  frontend/src/i18n/locales/en/glossary.json
  frontend/src/i18n/locales/es/glossary.json
  frontend/src/i18n/locales/fr/glossary.json
  frontend/src/i18n/locales/hi/glossary.json
  frontend/src/i18n/locales/it/glossary.json
  frontend/src/i18n/locales/ja/glossary.json
  frontend/src/i18n/locales/ko/glossary.json
  frontend/src/i18n/locales/pt/glossary.json
  frontend/src/i18n/locales/ta/glossary.json
  frontend/src/i18n/locales/zh-tw/glossary.json
  frontend/src/i18n/locales/zh/glossary.json
Labels: lgtm, cncf-cla: yes, approved, size/M

#3944 frontend: fix: correct CPU/Memory tooltip positioning in Nodes table
  frontend/src/components/common/Chart.tsx
Labels: lgtm, cncf-cla: yes, size/S, approved

#3958 frontend: EditButton: close actions menu on edit click
  frontend/src/components/common/Resource/EditButton.tsx
Labels: lgtm, cncf-cla: yes, approved, size/XS

#3950 frontend: Projects: Add ability to register custom delete button for projects
  frontend/src/components/project/ProjectDeleteButton.tsx
  frontend/src/components/project/ProjectDetails.tsx
  frontend/src/plugin/__snapshots__/pluginLib.snapshot
  frontend/src/plugin/registry.tsx
  frontend/src/redux/projectsSlice.ts
  plugins/examples/projects/src/index.tsx
Labels: cncf-cla: yes, approved, size/M

#3960 frontend: Layout: Add loader for backend connection
  frontend/src/App.test.tsx
  frontend/src/components/App/Layout.tsx
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/hi/translation.json
  frontend/src/i18n/locales/it/translation.json
  frontend/src/i18n/locales/ja/translation.json
  frontend/src/i18n/locales/ko/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/ta/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
  frontend/src/i18n/locales/zh/translation.json
Labels: lgtm, cncf-cla: yes, approved, size/M

#3962 Add more rule support to httproute
  frontend/src/components/common/NameValueTable/NameValueTable.tsx
  frontend/src/components/common/Resource/Resource.tsx
  frontend/src/components/gateway/HTTPRouteDetails.stories.tsx
  frontend/src/components/gateway/HTTPRouteDetails.tsx
  frontend/src/components/gateway/HTTPRouteList.stories.tsx
  frontend/src/components/gateway/__snapshots__/HTTPRouteDetails.Basic.stories.storyshot
  frontend/src/components/gateway/__snapshots__/HTTPRouteDetails.Empty.stories.storyshot
  frontend/src/components/gateway/__snapshots__/HTTPRouteList.Items.stories.storyshot
  frontend/src/components/gateway/storyHelper.ts
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/hi/translation.json
  frontend/src/i18n/locales/it/translation.json
  frontend/src/i18n/locales/ja/translation.json
  frontend/src/i18n/locales/ko/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/ta/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
  frontend/src/i18n/locales/zh/translation.json
Labels: lgtm, cncf-cla: yes, approved, size/XXL

#3963 fix: add fallback for idpIssuerURL
  backend/cmd/headlamp.go
Labels: lgtm, cncf-cla: yes, approved, size/XS

#3969 app: Fix glob pattern on windows for setup-plugins.js
  app/scripts/setup-plugins.js
Labels: lgtm, cncf-cla: yes, size/S, approved

#3971 frontend: Fix createRouteURL not being able to lookup routes from redux
  frontend/src/App.tsx
  frontend/src/components/Sidebar/NavigationTabs.tsx
  frontend/src/lib/router/createRouteURL.tsx
  frontend/src/lib/router/index.tsx
Labels: cncf-cla: yes, approved, size/M
