Repository kubernetes-sigs/headlamp, pull requests merged in 2025-01, with the labels that each got.

#2563 frontend: Add websocket multiplexer
  backend/cmd/headlamp.go
  backend/cmd/multiplexer.go
  backend/cmd/multiplexer_test.go
  frontend/package.json
  frontend/src/components/common/Resource/index.test.ts
  frontend/src/components/common/index.test.ts
  frontend/src/helpers/index.ts
  frontend/src/lib/k8s/api/v2/hooks.ts
  frontend/src/lib/k8s/api/v2/useKubeObjectList.test.tsx
  frontend/src/lib/k8s/api/v2/useKubeObjectList.ts
  frontend/src/lib/k8s/api/v2/webSocket.test.ts
  frontend/src/lib/k8s/api/v2/webSocket.ts
  frontend/src/plugin/__snapshots__/pluginLib.snapshot
Labels: size:XXL, lgtm, multi

#2731 backend: prevent panic in WebSocket multiplexer
  backend/cmd/multiplexer.go
  backend/cmd/multiplexer_test.go
  frontend/src/lib/k8s/api/v2/KubeList.ts
  frontend/src/lib/k8s/api/v2/useKubeObjectList.ts
  frontend/src/lib/k8s/api/v2/webSocket.ts
Labels: size:L, lgtm

#2727 frontend: Add TimeAgo component that displays and auto refreshes time
  frontend/src/components/common/Label.tsx
Labels: size:S, lgtm

#2638 frontend Sidebar: Improve performance by moving isSelected logic to the parent component
  frontend/src/components/Sidebar/Sidebar.tsx
  frontend/src/components/Sidebar/SidebarItem.tsx
  frontend/src/components/Sidebar/Sidebaritem.stories.tsx
Labels: frontend, performance, size:M, lgtm

#2705 charts: Reorganize and Enhance the Structure
  charts/headlamp/README.md
Labels: size:L, lgtm

#2603 frontend: TopBar: Hide menu on mobile when empty
  frontend/src/components/App/TopBar.tsx
Labels: frontend, mobile, size:S, lgtm

#2504 frontend: add support for gateway-api
  frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarClosed.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarOpen.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.SelectedItemWithSidebarOmitted.stories.storyshot
  frontend/src/components/Sidebar/prepareRoutes.ts
  frontend/src/components/gateway/ClassDetails.stories.tsx
  frontend/src/components/gateway/ClassDetails.tsx
  frontend/src/components/gateway/ClassList.stories.tsx
  frontend/src/components/gateway/ClassList.tsx
  frontend/src/components/gateway/GRPCRouteDetails.stories.tsx
  frontend/src/components/gateway/GRPCRouteDetails.tsx
  frontend/src/components/gateway/GRPCRouteList.stories.tsx
  frontend/src/components/gateway/GRPCRouteList.tsx
  frontend/src/components/gateway/GatewayDetails.stories.tsx
  frontend/src/components/gateway/GatewayDetails.tsx
  frontend/src/components/gateway/GatewayList.stories.tsx
  frontend/src/components/gateway/GatewayList.tsx
  frontend/src/components/gateway/HTTPRouteDetails.stories.tsx
  frontend/src/components/gateway/HTTPRouteDetails.tsx
  frontend/src/components/gateway/HTTPRouteList.stories.tsx
  frontend/src/components/gateway/HTTPRouteList.tsx
  frontend/src/components/gateway/__snapshots__/ClassDetails.Basic.stories.storyshot
  frontend/src/components/gateway/__snapshots__/ClassList.Items.stories.storyshot
  frontend/src/components/gateway/__snapshots__/GRPCRouteDetails.Basic.stories.storyshot
  frontend/src/components/gateway/__snapshots__/GRPCRouteList.Items.stories.storyshot
  frontend/src/components/gateway/__snapshots__/GatewayDetails.Basic.stories.storyshot
  frontend/src/components/gateway/__snapshots__/GatewayList.Items.stories.storyshot
  frontend/src/components/gateway/__snapshots__/HTTPRouteDetails.Basic.stories.storyshot
  frontend/src/components/gateway/__snapshots__/HTTPRouteList.Items.stories.storyshot
  frontend/src/components/gateway/storyHelper.ts
  frontend/src/components/gateway/utils.tsx
  frontend/src/i18n/locales/de/glossary.json
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/glossary.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/glossary.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/glossary.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/pt/glossary.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/glossary.json
  frontend/src/i18n/locales/zh-tw/translation.json
  frontend/src/lib/k8s/gateway.ts
  frontend/src/lib/k8s/gatewayClass.ts
  frontend/src/lib/k8s/grpcRoute.ts
  frontend/src/lib/k8s/httpRoute.ts
  frontend/src/lib/k8s/index.test.ts
  frontend/src/lib/k8s/index.ts
  frontend/src/lib/router.tsx
  frontend/src/plugin/__snapshots__/pluginLib.snapshot
Labels: size:XXL, lgtm

#2735 backend: Fix two races
  backend/cmd/multiplexer_test.go
  backend/pkg/cache/cache.go
Labels: bug, backend, size:S, lgtm

#2741 backend: enhance WSConnLock with thread-safety
  backend/cmd/multiplexer.go
  backend/cmd/multiplexer_test.go
Labels: size:XL, lgtm

#2743 i18n: fix templating in fr translation
  frontend/src/i18n/locales/fr/translation.json
Labels: size:XS, lgtm

#2744 frontend: Add missing base url in useWebSocket hook
  frontend/src/lib/k8s/api/v2/webSocket.ts
Labels: size:XS

#2745 frontend: CronJob details refactor
  frontend/src/components/cronjob/Details.tsx
  frontend/src/lib/k8s/KubeObject.ts
  frontend/src/lib/k8s/api/v1/factories.ts
Labels: size:L, lgtm

#2739 frontend: Fix createRouteURL to match routes by name
  frontend/src/lib/router.tsx
Labels: size:S, lgtm

#2754 frontend: fix websocket logs errors in tests
  frontend/src/lib/k8s/api/v2/webSocket.test.ts
  frontend/src/lib/k8s/api/v2/webSocket.ts
Labels: bug, frontend, size:M, lgtm, multi

#2757 ADOPTERS.md: Add Oracle / OCNE
  ADOPTERS.md
Labels: size:XS

#2759 docs/platforms: Add CNCF integrations table
  docs/platforms.md
Labels: documentation, size:S, lgtm

#2762 docs: Add Flatpak to platforms with comment about external tools
  docs/platforms.md
Labels: size:XS, lgtm

#2768 docs: Add section on running external tools in flatpak to installation
  docs/installation/desktop/linux-installation.md
  docs/platforms.md
Labels: size:S, lgtm

#2763 docs: Add mention of monthly community meeting
  README.md
  docs/faq.md
  docs/index.md
Labels: size:S

#2756 backend: Prevent flashing terminal on Windows
  app/electron/main.ts
  backend/pkg/exec/exec.go
  backend/pkg/exec/exec_test.go
  backend/pkg/exec/syscallattr_other.go
  backend/pkg/exec/syscallattr_windows.go
  backend/pkg/exec/testdata/test-plugin.sh
  backend/pkg/kubeconfig/kubeconfig.go
Labels: size:XXL

#2766 frontend: Quick fix for a case when no endpoints are available for the resource
  frontend/.storybook/baseMocks.ts
  frontend/src/components/gateway/ClassDetails.stories.tsx
  frontend/src/components/gateway/ClassList.stories.tsx
  frontend/src/components/gateway/GRPCRouteDetails.stories.tsx
  frontend/src/components/gateway/GatewayDetails.stories.tsx
  frontend/src/components/gateway/GatewayList.stories.tsx
  frontend/src/components/gateway/HTTPRouteDetails.stories.tsx
  frontend/src/components/gateway/__snapshots__/ClassDetails.Basic.stories.storyshot
  frontend/src/lib/k8s/api/v2/hooks.ts
  frontend/src/lib/k8s/api/v2/useKubeObjectList.ts
Labels: size:L, lgtm

#2752 frontend: EditorDialog: Remove unneeded Monaco override
  frontend/src/components/common/Resource/EditorDialog.tsx
Labels: bug, frontend, regression, size:S, lgtm

#2772 frontend: headlamp-plugin: Fix dependencies with audit fix
  frontend/package-lock.json
  plugins/headlamp-plugin/package-lock.json
Labels: frontend, dependencies, headlamp-plugin, size:XS

#2755 storybook: Add workaround for the circular dependecy crash
  frontend/.storybook/preview.tsx
  frontend/src/components/gateway/ClassDetails.stories.tsx
  frontend/src/storybook.test.tsx
Labels: bug, frontend, size:S, lgtm

#2775 frontend: Fix namespace selection when allowed namespaces is set
  frontend/src/lib/k8s/api/v2/useKubeObjectList.ts
Labels: size:XS, lgtm

#2778 Dockerfile: Update alpine to 3.20.4
  Dockerfile
  Dockerfile.plugins
Labels: dependencies, security, container, size:XS

#2774 frontend: Add beta label to Gateway
  frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarClosed.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarOpen.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.SelectedItemWithSidebarOmitted.stories.storyshot
  frontend/src/components/Sidebar/prepareRoutes.ts
  frontend/src/i18n/locales/de/glossary.json
  frontend/src/i18n/locales/en/glossary.json
  frontend/src/i18n/locales/es/glossary.json
  frontend/src/i18n/locales/fr/glossary.json
  frontend/src/i18n/locales/pt/glossary.json
  frontend/src/i18n/locales/zh-tw/glossary.json
Labels: size:S

#2777 backend: Update some CVE dependencies
  backend/go.mod
  backend/go.sum
Labels: backend, dependencies, security, size:S, lgtm

#2776 Revert "Merge pull request #2615 from farodin91/refactor-settings-cluster"
  frontend/src/components/App/Settings/AllowedNamespaces.tsx
  frontend/src/components/App/Settings/CustomClusterName.tsx
  frontend/src/components/App/Settings/DefaultNamespace.tsx
  frontend/src/components/App/Settings/SettingsCluster.tsx
Labels: bug, frontend, regression, size:XL

#2780 chocolatey: Bump Headlamp version to 0.28.0
  app/windows/chocolatey/headlamp.nuspec
  app/windows/chocolatey/tools/chocolateyinstall.ps1
Labels: size:XS

#2789 charts: Add support for custom ingress labels
  charts/headlamp/README.md
  charts/headlamp/templates/ingress.yaml
  charts/headlamp/tests/expected_templates/default.yaml
  charts/headlamp/tests/expected_templates/extra-args.yaml
  charts/headlamp/tests/expected_templates/extra-manifests.yaml
  charts/headlamp/tests/expected_templates/oidc-create-secret.yaml
  charts/headlamp/tests/expected_templates/oidc-directly-env.yaml
  charts/headlamp/tests/expected_templates/oidc-directly.yaml
  charts/headlamp/tests/expected_templates/oidc-external-secret.yaml
  charts/headlamp/tests/expected_templates/volumes-added.yaml
  charts/headlamp/values.yaml
Labels: size:L

#2797 Update platforms.md with K0s
  docs/platforms.md
Labels: size:XS, lgtm

#2795 headlamp-plugin: Change the version for the template's package.json
  plugins/headlamp-plugin/template/package.json
Labels: size:XS

#2758 feat(helm): add extended service values
  charts/headlamp/templates/service.yaml
  charts/headlamp/values.schema.json
  charts/headlamp/values.yaml
Labels: size:M

#2808 frontend: plugins: Remove unused @types/nock pkg
  frontend/package-lock.json
  frontend/package.json
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: frontend, dependencies, size:XS

#2809 frontend: Update vite to 5.4.14
  frontend/package-lock.json
  frontend/package.json
Labels: frontend, development, size:XS

#2794 frontend: Fallback to default namespace found in the kubeconfig when all namespaces fail to load
  frontend/src/components/common/NamespacesAutocomplete.tsx
Labels: size:M, lgtm
