Repository kubernetes-sigs/headlamp, pull requests merged in 2025-02, with the labels that each got.

#2835 charts: Fix value.schema.json
  charts/headlamp/tests/expected_templates/extra-args.yaml
  charts/headlamp/tests/expected_templates/extra-manifests.yaml
  charts/headlamp/tests/expected_templates/oidc-create-secret.yaml
  charts/headlamp/tests/expected_templates/oidc-directly-env.yaml
  charts/headlamp/tests/expected_templates/oidc-directly.yaml
  charts/headlamp/tests/expected_templates/oidc-external-secret.yaml
  charts/headlamp/tests/expected_templates/volumes-added.yaml
  charts/headlamp/values.schema.json
Labels: size:S, lgtm

#2837 app: Disable shell option for spawn in run-command
  app/electron/main.ts
Labels: size:XS, lgtm

#2838 app: Disable run-command
  app/electron/main.ts
Labels: size:XS, lgtm

#2834 Docs: Fix contributing doc test and formatting instruction
  docs/contributing.md
Labels: size:XS

#2843 portforward: Fix recursive loading
  backend/pkg/portforward/handler.go
  frontend/src/lib/k8s/api/v1/portForward.ts
Labels: size:M, lgtm

#2817 Show plugin package URL for user confirmation
  app/electron/locales/de/app.json
  app/electron/locales/en/app.json
  app/electron/locales/es/app.json
  app/electron/locales/fr/app.json
  app/electron/locales/pt/app.json
  app/electron/main.ts
  app/electron/plugin-management.ts
Labels: size:L

#2813 docs: remove redundant backend, frontend build commands before building app
  docs/development/index.md
Labels: size:XS, lgtm

#2844 frontend: ScaleButton and RestartButton: Storybook added
  frontend/src/components/common/Resource/RestartButton.stories.tsx
  frontend/src/components/common/Resource/ScaleButton.stories.tsx
  frontend/src/components/common/Resource/__snapshots__/RestartButton.DeploymentExample.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/RestartButton.StatefulSetExample.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/ScaleButton.DeploymentExample.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/ScaleButton.ReplicaSetExample.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/ScaleButton.StatefulSetExample.stories.storyshot
Labels: size:L, lgtm

#2826 Frontend: NetworkPolicyList Story added
  frontend/src/components/networkpolicy/NextworkPolicy.stories.tsx
  frontend/src/components/networkpolicy/__snapshots__/NextworkPolicy.Default.stories.storyshot
Labels: size:L, lgtm

#2825 Frontend: BackLink: StoryBooks and its snapshots added
  frontend/src/components/common/BackLink/BackLink.stories.tsx
  frontend/src/components/common/BackLink/__snapshots__/BackLink.CustomLink.stories.storyshot
  frontend/src/components/common/BackLink/__snapshots__/BackLink.Default.stories.storyshot
Labels: size:M, lgtm

#2847 frontend: app: Pass backendToken via IPC
  app/electron/main.ts
  app/electron/preload.ts
  frontend/src/components/App/AppContainer.tsx
  frontend/src/helpers/index.ts
Labels: frontend, app, size:M, lgtm

#2851 frontend: Update vitest to 2.1.9
  frontend/package-lock.json
  frontend/package.json
Labels: frontend, dependencies, size:XS

#2816 backend: refactor: refreshAndCacheNewToken in headlamp.go
  backend/cmd/headlamp.go
Labels: size:L, lgtm

#2858 github: Make Mac build job fail if signing failed
  .github/workflows/app-artifacts-mac.yml
Labels: size:XS

#2839 frontend: added tests for lib/units.ts and lib/cluster.ts files
  frontend/src/lib/cluster.test.ts
  frontend/src/lib/cluster.ts
  frontend/src/lib/units.test.ts
Labels: size:L, lgtm

#2859 github: Use a newer version of ESRP
  .github/workflows/app-artifacts-mac.yml
Labels: size:XS

#2845 frontend: Add story for `Deployments`
  frontend/src/components/deployments/List.stories.tsx
  frontend/src/components/deployments/__snapshots__/List.Deployments.stories.storyshot
Labels: frontend, size:XXL, lgtm

#2830 frontend: OauthPopup: Added stories
  frontend/src/components/oidcauth/OauthPopup.stories.tsx
  frontend/src/components/oidcauth/__snapshots__/OauthPopup.Default.stories.storyshot
  frontend/src/components/oidcauth/__snapshots__/OauthPopup.WithDimensions.stories.storyshot
Labels: size:M, lgtm

#2824 frontend: add Chooser componnent stories
  frontend/src/components/cluster/Chooser.stories.tsx
  frontend/src/components/cluster/__snapshots__/Chooser.Closed.stories.storyshot
  frontend/src/components/cluster/__snapshots__/Chooser.ManyClusters.stories.storyshot
  frontend/src/components/cluster/__snapshots__/Chooser.NoClusters.stories.storyshot
  frontend/src/components/cluster/__snapshots__/Chooser.Normal.stories.storyshot
  frontend/src/components/cluster/__snapshots__/Chooser.SingleCluster.stories.storyshot
Labels: size:XXL, lgtm

#2823 frontend: Add clusterChooser componnent stories
  frontend/src/components/cluster/ClusterChooser.stories.tsx
  frontend/src/components/cluster/__snapshots__/ClusterChooser.LongClusterName.stories.storyshot
  frontend/src/components/cluster/__snapshots__/ClusterChooser.NoCluster.stories.storyshot
  frontend/src/components/cluster/__snapshots__/ClusterChooser.Normal.stories.storyshot
  frontend/src/components/cluster/__snapshots__/ClusterChooser.SpecialCharacters.stories.storyshot
Labels: size:L, lgtm

#2822 frontend: Add tests for `@apidevtools/swagger-parser`
  frontend/src/lib/swagger-parser.k8s.test.ts
Labels: size:L, lgtm

#2819 frontend: Add new `LogViewer` stories
  frontend/src/components/common/LogViewer.stories.tsx
  frontend/src/components/common/__snapshots__/LogViewer.BasicLogs.stories.storyshot
  frontend/src/components/common/__snapshots__/LogViewer.ColoredLogs.stories.storyshot
  frontend/src/components/common/__snapshots__/LogViewer.LiveUpdatingLogs.stories.storyshot
  frontend/src/components/common/__snapshots__/LogViewer.LogOverflow.stories.storyshot
  frontend/src/components/common/__snapshots__/LogViewer.ReconnectToSeeLogs.stories.storyshot
  frontend/src/components/common/__snapshots__/LogViewer.TopActions.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodLogs.Logs.stories.storyshot
  frontend/src/storybook.test.tsx
Labels: size:XXL, lgtm

#2853 frontend: MatchExpressions: Add storybook
  frontend/src/components/common/Resource/MatchExpressions.stories.tsx
  frontend/src/components/common/Resource/__snapshots__/MatchExpressions.Default.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/MatchExpressions.WithExpressions.stories.storyshot
Labels: size:M, lgtm

#2862 frontend: NextworkPolicy: Fix story snapshot issue
  frontend/src/components/networkpolicy/__snapshots__/NextworkPolicy.Default.stories.storyshot
Labels: size:M, lgtm

#2840 frontend: PluginSettingsDetail: ToDo completed
  frontend/src/components/App/PluginSettings/PluginSettingsDetails.tsx
Labels: size:S, lgtm

#2863 github: Stop automatically creating minikube PR
  .github/workflows/pr-to-update-minikube.yml
Labels: size:XS

#2866 chocolatey: Bump Headlamp version to 0.28.1
  app/windows/chocolatey/headlamp.nuspec
  app/windows/chocolatey/tools/chocolateyinstall.ps1
Labels: size:XS

#2872 frontend: Add story for `DocsViewer` component
  frontend/src/components/common/Resource/DocsViewer.stories.tsx
  frontend/src/components/common/Resource/DocsViewer.tsx
  frontend/src/components/common/Resource/__snapshots__/DocsViewer.CommentOnlyDocumentation.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/DocsViewer.ErrorDocumentation.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/DocsViewer.IncompleteDocumentation.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/DocsViewer.TypicalDocumentation.stories.storyshot
Labels: size:L, lgtm

#2870 frontend: headlamp-plugin: Update dependencies
  frontend/package-lock.json
  frontend/package.json
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: frontend, dependencies, headlamp-plugin, size:XS, lgtm

#2860 backend: headlamp.go: fix incorrect implementation of JWT token expir…
  backend/cmd/headlamp.go
  backend/cmd/headlamp_test.go
Labels: size:S, lgtm

#2717 frontend: Refactor prepareSidebarItems into a hook
  frontend/src/components/Sidebar/NavigationTabs.tsx
  frontend/src/components/Sidebar/Sidebar.tsx
  frontend/src/components/Sidebar/prepareRoutes.ts
  frontend/src/components/Sidebar/useSidebarItems.test.tsx
  frontend/src/components/Sidebar/useSidebarItems.ts
Labels: size:XL, lgtm

#2715 frontend: Improve scroll bars
  frontend/src/components/App/Layout.tsx
  frontend/src/components/App/TopBar.tsx
  frontend/src/components/App/__snapshots__/TopBar.NoToken.stories.storyshot
  frontend/src/components/App/__snapshots__/TopBar.OneCluster.stories.storyshot
  frontend/src/components/App/__snapshots__/TopBar.ProcessorAction.stories.storyshot
  frontend/src/components/App/__snapshots__/TopBar.Token.stories.storyshot
  frontend/src/components/App/__snapshots__/TopBar.TwoCluster.stories.storyshot
  frontend/src/components/Sidebar/Sidebar.tsx
  frontend/src/components/Sidebar/__snapshots__/Sidebar.HomeSidebarClosed.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.HomeSidebarOpen.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarClosed.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarOpen.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.SelectedItemWithSidebarOmitted.stories.storyshot
  frontend/src/lib/themes.ts
Labels: frontend, size:L, lgtm

#2867 github: Chocolatey needs to be updated always on the main branch
  .github/workflows/pr-to-update-choco.yml
Labels: size:XS, lgtm

#2874 frontend: CreateButton: Add Storybook
  frontend/src/components/common/Resource/CreateButton.stories.tsx
  frontend/src/components/common/Resource/__snapshots__/CreateButton.Default.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/CreateButton.NarrowButton.stories.storyshot
Labels: size:M, lgtm

#2829 Frontend: Add Storybook Stories for Notifications Component
  frontend/src/components/App/Notifications/List/List.stories.tsx
  frontend/src/components/App/Notifications/List/List.tsx
  frontend/src/components/App/Notifications/List/index.tsx
  frontend/src/components/App/Notifications/Notifications.stories.tsx
  frontend/src/components/App/Notifications/Notifications.tsx
  frontend/src/components/App/Notifications/__snapshots__/Notifications.MixedNotifications.stories.storyshot
  frontend/src/components/App/Notifications/__snapshots__/Notifications.NoNotifications.stories.storyshot
  frontend/src/components/App/Notifications/__snapshots__/Notifications.WithMultipleClusters.stories.storyshot
  frontend/src/components/App/Notifications/__snapshots__/Notifications.WithReadNotifications.stories.storyshot
  frontend/src/components/App/Notifications/__snapshots__/Notifications.WithUnreadNotifications.stories.storyshot
  frontend/src/components/App/Notifications/index.tsx
Labels: size:XL, lgtm

#2879 frontend: NavigationTabs: Move early return after all hooks to prevent a crash
  frontend/src/components/Sidebar/NavigationTabs.tsx
Labels: size:S, lgtm

#1995 app: Add checkCommandConsent dialog for checking az/minikube/etc
  app/electron/main.ts
Labels: security, plugins, app, size:M, minikube

#2884 eslint-config: Update cross-spawn to 7.0.6
  eslint-config/package-lock.json
  eslint-config/package.json
Labels: dependencies, size:XS, lgtm

#2882 app: runCmd: Extract handleRunCommand functionality from main.ts
  app/.gitignore
  app/electron/main.ts
  app/electron/runCmd.ts
  app/package.json
Labels: app, size:L

#2881 frontend: NetworkPolicy: Add storybooks
  frontend/src/components/networkpolicy/NetworkPolicyDetails.stories.tsx
  frontend/src/components/networkpolicy/NetworkPolicyList.stories.tsx
  frontend/src/components/networkpolicy/__snapshots__/NetworkPolicyDetails.Default.stories.storyshot
  frontend/src/components/networkpolicy/__snapshots__/NetworkPolicyDetails.NoName.stories.storyshot
  frontend/src/components/networkpolicy/__snapshots__/NetworkPolicyDetails.NoNamespace.stories.storyshot
  frontend/src/components/networkpolicy/__snapshots__/NetworkPolicyDetails.NoProps.stories.storyshot
  frontend/src/components/networkpolicy/__snapshots__/NetworkPolicyList.Default.stories.storyshot
Labels: size:L, lgtm

#2815 docs: document running the app while backend, frontend are running externally
  Makefile
  docs/development/index.md
Labels: size:S, lgtm

#2827 frontend: Add restart bulk action for resources list
  frontend/src/components/common/ConfirmDialog.tsx
  frontend/src/components/common/Resource/ResourceTableMultiActions.tsx
  frontend/src/components/common/Resource/RestartButton.tsx
  frontend/src/components/common/Resource/RestartMultipleButton.tsx
  frontend/src/components/common/Resource/__snapshots__/RestartButton.DeploymentExample.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/RestartButton.StatefulSetExample.stories.storyshot
  frontend/src/components/common/Resource/index.test.ts
  frontend/src/components/common/__snapshots__/ConfirmDialog.ConfirmDialog.stories.storyshot
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
  frontend/src/plugin/__snapshots__/pluginLib.snapshot
  frontend/src/redux/headlampEventSlice.ts
Labels: size:L, lgtm

#2888 headlamp-plugin: Add fuse.js dependency
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: size:XS

#2889 frontend: networkpolicy: Remove snapshot tests to fix main
  frontend/src/components/networkpolicy/NetworkPolicyDetails.stories.tsx
  frontend/src/components/networkpolicy/NetworkPolicyList.stories.tsx
  frontend/src/components/networkpolicy/__snapshots__/NetworkPolicyDetails.Default.stories.storyshot
  frontend/src/components/networkpolicy/__snapshots__/NetworkPolicyDetails.NoName.stories.storyshot
  frontend/src/components/networkpolicy/__snapshots__/NetworkPolicyDetails.NoNamespace.stories.storyshot
  frontend/src/components/networkpolicy/__snapshots__/NetworkPolicyDetails.NoProps.stories.storyshot
  frontend/src/components/networkpolicy/__snapshots__/NetworkPolicyList.Default.stories.storyshot
Labels: size:XL, lgtm

#2886 frontend: headlamp-plugins: Update react-window to 1.8.11
  frontend/package-lock.json
  frontend/package.json
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: size:XS

#2891 docs: Change ingress.className on README to ingress.ingressClassName
  charts/headlamp/README.md
Labels: size:XS

#2653 frontend: Add Pod list metrics
  frontend/src/components/common/Resource/Resource.tsx
  frontend/src/components/common/Table/Table.tsx
  frontend/src/components/namespace/NamespaceDetails.stories.tsx
  frontend/src/components/pod/List.tsx
  frontend/src/components/pod/PodList.stories.tsx
  frontend/src/components/pod/__snapshots__/PodList.Items.stories.storyshot
  frontend/src/lib/k8s/KubeObject.ts
  frontend/src/lib/k8s/PodMetrics.ts
  frontend/src/lib/k8s/api/v2/useKubeObjectList.ts
Labels: enhancement, frontend, size:L, lgtm

#2856 frontend: EditorDialog: Handle null YAML in docs tab
  frontend/src/components/common/Resource/DocsViewer.tsx
  frontend/src/components/common/Resource/EditorDialog.tsx
  frontend/src/components/common/Resource/__snapshots__/EditorDialog.EditorDialogWithResource.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/EditorDialog.ExtraActions.stories.storyshot
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
Labels: bug, frontend, size:M, lgtm

#2910 backend: Update golang@1.24 and golangci-lint@v1.64
  .github/workflows/app-artifacts-linux.yml
  .github/workflows/app-artifacts-mac.yml
  .github/workflows/app-artifacts-win.yml
  .github/workflows/app.yml
  .github/workflows/backend-test.yml
  Dockerfile
  Makefile
  backend/.golangci.yml
  backend/cmd/headlamp.go
  backend/cmd/headlamp_test.go
  backend/cmd/multiplexer_test.go
  backend/cmd/stateless.go
  backend/cmd/stateless_test.go
  backend/go.mod
  backend/pkg/config/config.go
  backend/pkg/config/config_test.go
  backend/pkg/helm/release.go
  backend/pkg/kubeconfig/file.go
  backend/pkg/plugins/plugins.go
  backend/pkg/plugins/plugins_test.go
  backend/pkg/portforward/handler.go
  docs/development/index.md
Labels: backend, dependencies, quality, size:L, lgtm

#2905 frontend: TimeZoneSelect: Add Storybooks
  frontend/src/components/common/TimezoneSelect/TimezoneSelect.stories.tsx
  frontend/src/components/common/TimezoneSelect/__snapshots__/TimezoneSelect.Default.stories.storyshot
  frontend/src/components/common/TimezoneSelect/__snapshots__/TimezoneSelect.NoInitialValue.stories.storyshot
Labels: size:L, lgtm

#2832 Plugins: added Resource CircularChart example plugin
  frontend/src/components/cluster/Overview.tsx
  frontend/src/plugin/__snapshots__/pluginLib.snapshot
  frontend/src/plugin/registry.tsx
  frontend/src/redux/overviewChartsSlice.ts
  frontend/src/redux/reducers/reducers.tsx
  plugins/examples/resource-charts/.vscode/extensions.json
  plugins/examples/resource-charts/.vscode/settings.json
  plugins/examples/resource-charts/.vscode/tasks.json
  plugins/examples/resource-charts/README.md
  plugins/examples/resource-charts/package-lock.json
  plugins/examples/resource-charts/package.json
  plugins/examples/resource-charts/src/headlamp-plugin.d.ts
  plugins/examples/resource-charts/src/index.tsx
  plugins/examples/resource-charts/src/storybook.test.tsx
  plugins/examples/resource-charts/src/types.d.ts
  plugins/examples/resource-charts/tsconfig.json
Labels: documentation, enhancement, plugins, size:L

#2915 backend: Do not include clusters with errors when loading them
  backend/cmd/headlamp.go
  backend/cmd/headlamp_test.go
  backend/cmd/headlamp_testdata/kubeconfig_partialcontextvalid
  backend/pkg/kubeconfig/kubeconfig.go
  backend/pkg/kubeconfig/kubeconfig_test.go
Labels: bug, backend, regression, blocker, size:M, lgtm

#2875 frontend: remove obsolete API call for CronJobs
  frontend/src/lib/k8s/cronJob.ts
Labels: size:XS, lgtm

#2914 frontend: Fix test warnings and misconfiguration
  frontend/src/components/App/Notifications/Notifications.stories.tsx
  frontend/src/components/gateway/GRPCRouteDetails.stories.tsx
  frontend/src/components/gateway/GRPCRouteList.stories.tsx
  frontend/src/components/gateway/HTTPRouteDetails.stories.tsx
  frontend/src/components/gateway/HTTPRouteList.stories.tsx
  frontend/src/plugin/pluginLib.test.ts
  frontend/src/storybook.test.tsx
Labels: size:M, lgtm

#2746 app: Remember zoom level after restarts
  app/electron/main.ts
Labels: enhancement, desktop, size:M, lgtm

#2924 CI: Fix CI crash - Update actions/cache action to v4.2.1
  .github/workflows/build-container.yml
Labels: bug, CI, size:XS, lgtm

#2931 backend: Move wsMultiplexer handler so it's not skipped without dynamic cluster feature
  backend/cmd/headlamp.go
Labels: size:XS, lgtm

#2934 frontend: redux: add unit tests
  frontend/src/redux/actionButtonsSlice.test.ts
  frontend/src/redux/configSlice.test.ts
  frontend/src/redux/overviewChartsSlice.test.ts
Labels: size:L, lgtm

#2908 frontend: fix `DocsViewer` stories to use `msw` handlers
  frontend/src/components/common/Resource/DocsViewer.stories.tsx
  frontend/src/components/common/Resource/DocsViewer.tsx
  frontend/src/components/common/Resource/__snapshots__/DocsViewer.CommentOnlyDocumentation.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/DocsViewer.ErrorDocumentation.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/DocsViewer.NoDocumentation.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/DocsViewer.NoMatchingDocumentation.stories.storyshot
  frontend/src/lib/docs.ts
Labels: size:L, lgtm

#2926 frontend: Fix broken link for involved objects in the overview
  frontend/src/lib/k8s/event.ts
Labels: size:XS

#2929 frontend: headlamp-plugin: Update dependencies
  frontend/package-lock.json
  frontend/package.json
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: frontend, dependencies, headlamp-plugin, size:XS, lgtm

#2907 frontend: global searchbar: Fix multiple clusterSettings items
  frontend/src/components/globalSearch/GlobalSearchContent.tsx
Labels: size:XS

#2581 frontend: Add feature to view deploy/rs/ds logs
  frontend/src/components/common/Resource/LogsButton.tsx
  frontend/src/components/common/Resource/index.test.ts
  frontend/src/components/common/Resource/index.tsx
  frontend/src/components/workload/Details.tsx
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
  frontend/src/lib/router.tsx
  frontend/src/plugin/__snapshots__/pluginLib.snapshot
Labels: size:XL, lgtm

#2940 backend: Add toolchain for those without latest go
  backend/go.mod
Labels: size:XS

#2909 frontend: Add tests for `docs.ts`
  frontend/src/lib/docs.test.ts
Labels: size:L, lgtm

#2942 frontend: Fix word breaking for min content columns
  frontend/src/components/common/Resource/__snapshots__/ResourceListView.OneHiddenColumn.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/ResourceTable.NameSearch.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/ResourceTable.NoFilter.stories.storyshot
  frontend/src/components/common/Resource/__snapshots__/ResourceTable.WithHiddenCols.stories.storyshot
  frontend/src/components/common/Table/Table.tsx
  frontend/src/components/configmap/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceDefinition.Details.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceDefinition.List.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceList.List.stories.storyshot
  frontend/src/components/cronjob/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/daemonset/__snapshots__/List.DaemonSets.stories.storyshot
  frontend/src/components/deployments/__snapshots__/List.Deployments.stories.storyshot
  frontend/src/components/endpoints/__snapshots__/EndpointList.Items.stories.storyshot
  frontend/src/components/gateway/__snapshots__/ClassList.Items.stories.storyshot
  frontend/src/components/gateway/__snapshots__/GRPCRouteList.Items.stories.storyshot
  frontend/src/components/gateway/__snapshots__/GatewayList.Items.stories.storyshot
  frontend/src/components/gateway/__snapshots__/HTTPRouteList.Items.stories.storyshot
  frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPAList.Items.stories.storyshot
  frontend/src/components/ingress/__snapshots__/ClassList.Items.stories.storyshot
  frontend/src/components/ingress/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/job/__snapshots__/JobList.Items.stories.storyshot
  frontend/src/components/lease/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/limitRange/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/namespace/__snapshots__/NamespaceList.Regular.stories.storyshot
  frontend/src/components/node/__snapshots__/List.Nodes.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodList.Items.stories.storyshot
  frontend/src/components/podDisruptionBudget/__snapshots__/pdbList.Items.stories.storyshot
  frontend/src/components/priorityClass/__snapshots__/priorityClassList.Items.stories.storyshot
  frontend/src/components/replicaset/__snapshots__/List.ReplicaSets.stories.storyshot
  frontend/src/components/resourceQuota/__snapshots__/resourceQuotaList.Items.stories.storyshot
  frontend/src/components/runtimeClass/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/secret/__snapshots__/List.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/ClaimList.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/ClassList.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/VolumeList.Items.stories.storyshot
  frontend/src/components/verticalPodAutoscaler/__snapshots__/VPAList.List.stories.storyshot
  frontend/src/components/webhookconfiguration/__snapshots__/MutatingWebhookConfigList.Items.stories.storyshot
  frontend/src/components/webhookconfiguration/__snapshots__/ValidatingWebhookConfigList.Items.stories.storyshot
Labels: bug, frontend, size:L

#2935 frontend: Fix incorrect links in sidebar after switching clusters
  frontend/src/components/App/TopBar.tsx
  frontend/src/components/Sidebar/SidebarItem.tsx
  frontend/src/lib/k8s/index.ts
Labels: bug, frontend, size:M

#1447 frontend: Add detail drawer mode
  frontend/src/components/App/Layout.tsx
  frontend/src/components/App/Settings/DrawerModeSettings.tsx
  frontend/src/components/App/Settings/Settings.tsx
  frontend/src/components/App/Settings/__snapshots__/Settings.General.stories.storyshot
  frontend/src/components/App/Settings/__snapshots__/Settings.stories.storyshot
  frontend/src/components/common/Link.stories.tsx
  frontend/src/components/common/Link.tsx
  frontend/src/components/common/Resource/DetailsDrawer.tsx
  frontend/src/components/common/Resource/ResourceTable.stories.tsx
  frontend/src/components/common/Resource/index.test.ts
  frontend/src/components/common/__snapshots__/Link.AutoTooltip.stories.storyshot
  frontend/src/components/common/__snapshots__/Link.ExplicitTooltip.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodList.Items.stories.storyshot
  frontend/src/components/resourceMap/details/KubeNodeDetails.tsx
  frontend/src/components/storage/__snapshots__/ClaimDetails.Base.stories.storyshot
  frontend/src/components/storage/__snapshots__/ClaimList.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/VolumeDetails.Base.stories.storyshot
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
  frontend/src/redux/drawerModeSlice.ts
  frontend/src/redux/reducers/reducers.tsx
Labels: size:XL

#2761 docs: release-guide.md: Add release-guide.md doc
  docs/development/release-guide.md
  docs/development/release-version.png
Labels: documentation, release, size:L

#2947 frontend: Fix DetailsDrawer to not mutate url when in app mode
  frontend/src/components/common/Resource/DetailsDrawer.tsx
Labels: size:XS

#2948 Dockerfile: Update alpine to 3.20.5
  Dockerfile.plugins
Labels: dependencies, security, container, size:XS, lgtm

#2941 frontend: Update useSidebarItems hooks to support extending default sidebar items
  frontend/src/components/Sidebar/useSidebarItems.test.tsx
  frontend/src/components/Sidebar/useSidebarItems.ts
Labels: bug, frontend, plugins, regression, size:L, lgtm

#2913 frontend: Update frontend dependencies
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/App/Notifications/Notifications.stories.tsx
  frontend/src/components/common/LogViewer.stories.tsx
  frontend/src/components/common/Resource/RestartButton.stories.tsx
  frontend/src/components/common/Resource/RestartMultipleButton.stories.tsx
  frontend/src/components/common/Resource/ScaleButton.stories.tsx
  frontend/src/components/common/__snapshots__/LogViewer.BasicLogs.stories.storyshot
  frontend/src/components/common/__snapshots__/LogViewer.LogOverflow.stories.storyshot
  frontend/src/components/common/__snapshots__/LogViewer.TopActions.stories.storyshot
  frontend/src/components/pod/PodLogs.stories.tsx
  frontend/src/components/pod/__snapshots__/PodLogs.Logs.stories.storyshot
  frontend/src/helpers/testHelpers.ts
  frontend/src/lib/k8s/api/v2/useKubeObjectList.test.tsx
  frontend/src/storybook.test.tsx
  frontend/vitest.config.ts
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: size:L, lgtm

#2951 chocolatey: Bump Headlamp version to 0.29.0
  app/windows/chocolatey/headlamp.nuspec
  app/windows/chocolatey/tools/chocolateyinstall.ps1
Labels: size:XS, lgtm

#2954 github: Add a new workflow to attach the release assets to a release
  .github/workflows/push-release-assets.yml
Labels: CI, size:L

#2953 app/scrips/push-release-assets: Fix running the script
  app/scripts/push-release-assets/package.json
  app/scripts/push-release-assets/push-release-assets.js
Labels: size:S

#2959 charts: make in-cluster arg configurable
  charts/headlamp/README.md
  charts/headlamp/templates/deployment.yaml
  charts/headlamp/values.yaml
Labels: size:XS, lgtm

#2861 frontend: Add e2e-tests for multiple clusters
  .github/workflows/build-container.yml
  e2e-tests/kubernetes-headlamp-ci.yaml
  e2e-tests/tests/dynamicCluster.spec.ts
  e2e-tests/tests/headlamp.spec.ts
  e2e-tests/tests/headlampPage.ts
  e2e-tests/tests/multiCluster.spec.ts
  e2e-tests/tests/namespaces.spec.ts
  e2e-tests/tests/namespacesPage.ts
  e2e-tests/tests/pluginSetting.spec.ts
  e2e-tests/tests/podsPage.spec.ts
  e2e-tests/tests/podsPage.ts
Labels: testing, quality, e2e-tests, size:L, lgtm, multi

#2957 Simplify push release assets
  .github/workflows/push-release-assets.yml
  app/scripts/push-release-assets/push-release-assets.js
Labels: size:M

#2938 backend: frontend: Pass authentication token to websocket multiplexer
  backend/cmd/multiplexer.go
  backend/cmd/multiplexer_test.go
  frontend/src/lib/k8s/api/v2/webSocket.test.ts
  frontend/src/lib/k8s/api/v2/webSocket.ts
Labels: bug, backend, regression, size:M, lgtm
