Repository kubernetes-sigs/headlamp, pull requests merged in 2025-05, with the labels that each got.

#3182 frontend: Add ability to register UI panels for plugins
  docs/development/plugins/functionality/images/side-panels-example.png
  docs/development/plugins/functionality/index.md
  frontend/src/components/App/Layout.tsx
  frontend/src/components/App/Notifications/List/List.stories.tsx
  frontend/src/components/App/RouteSwitcher.tsx
  frontend/src/components/App/Settings/Settings.tsx
  frontend/src/components/App/TopBar.stories.tsx
  frontend/src/components/App/TopBar.tsx
  frontend/src/components/App/VersionDialog.tsx
  frontend/src/components/Sidebar/Sidebar.stories.tsx
  frontend/src/components/Sidebar/Sidebar.tsx
  frontend/src/components/Sidebar/__snapshots__/Sidebar.HomeSidebarClosed.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.HomeSidebarOpen.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarClosed.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarOpen.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.SelectedItemWithSidebarOmitted.stories.storyshot
  frontend/src/components/cluster/Chooser.tsx
  frontend/src/components/common/Resource/DetailsDrawer.tsx
  frontend/src/components/common/Resource/ResourceTable.stories.tsx
  frontend/src/plugin/Plugins.tsx
  frontend/src/plugin/__snapshots__/pluginLib.snapshot
  frontend/src/plugin/registry.tsx
  frontend/src/redux/actions/actions.tsx
  frontend/src/redux/reducers/reducers.tsx
  frontend/src/redux/reducers/ui.tsx
  frontend/src/redux/stores/store.tsx
  frontend/src/redux/uiSlice.ts
  plugins/README.md
  plugins/examples/ui-panels/.gitignore
  plugins/examples/ui-panels/.vscode/extensions.json
  plugins/examples/ui-panels/.vscode/settings.json
  plugins/examples/ui-panels/.vscode/tasks.json
  plugins/examples/ui-panels/README.md
  plugins/examples/ui-panels/package-lock.json
  plugins/examples/ui-panels/package.json
  plugins/examples/ui-panels/src/headlamp-plugin.d.ts
  plugins/examples/ui-panels/src/index.tsx
  plugins/examples/ui-panels/tsconfig.json
Labels: frontend, lgtm, cncf-cla: yes, approved, size/XXL

#3194 frontend: workload: Stop loading list infinitely
  frontend/src/components/workload/Overview.tsx
Labels: kind/bug, frontend, lgtm, cncf-cla: yes, approved, size/XS

#3107 charts: Improve Helm chart template testing
  .github/workflows/helm-chart-template-test.yml
  Makefile
  charts/headlamp/README.md
  charts/headlamp/tests/expected_templates/default.yaml
  charts/headlamp/tests/expected_templates/extra-args.yaml
  charts/headlamp/tests/expected_templates/extra-manifests.yaml
  charts/headlamp/tests/expected_templates/oidc-create-secret.yaml
  charts/headlamp/tests/expected_templates/oidc-directly-env.yaml
  charts/headlamp/tests/expected_templates/oidc-directly.yaml
  charts/headlamp/tests/expected_templates/oidc-external-secret.yaml
  charts/headlamp/tests/expected_templates/volumes-added.yaml
  charts/headlamp/tests/readme.md
  charts/headlamp/tests/test.sh
  charts/headlamp/tests/update-version.sh
Labels: lgtm, cncf-cla: yes, approved, size/L

#3204 plugins: examples: ui-panels: add role attribute to UI panel components for accessibility
  plugins/examples/ui-panels/src/index.tsx
Labels: lgtm, cncf-cla: yes, approved, size/XS

#3203 frontend: Add lint rule for the license headers and add missing headers
  app/electron/i18next-parser.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/App/Home/ClusterContextMenu.tsx
  frontend/src/components/App/Home/ClusterTable.tsx
  frontend/src/components/App/Home/config.ts
  frontend/src/components/App/Home/customClusterNames.ts
  frontend/src/components/App/Settings/ThemePreview.tsx
  frontend/src/helpers/debugVerbose.ts
  frontend/src/i18n/i18next-parser.config.js
  frontend/src/i18n/tools/copy-translations.js
  frontend/src/i18n/tools/extract-empty-translations.js
  frontend/src/make-env.test.js
  frontend/src/redux/uiSlice.ts
  plugins/headlamp-plugin/bin/headlamp-plugin.js
  plugins/headlamp-plugin/config/setupTests.js
  plugins/headlamp-plugin/dependencies-sync.js
  plugins/headlamp-plugin/plugin-management/plugin-management.e2e.js
  plugins/headlamp-plugin/plugin-management/plugin-management.js
  plugins/headlamp-plugin/plugin-management/plugin-management.test.js
  plugins/headlamp-plugin/test-headlamp-plugin-published.js
  plugins/headlamp-plugin/test-headlamp-plugin.js
Labels: cncf-cla: yes, approved, size/L

#3210 plugins: examples: ui-panels: add aria-label attributes for improved accessibility
  plugins/examples/ui-panels/src/index.tsx
Labels: cncf-cla: yes, approved, size/XS

#3200 frontend: themeSlice: Use useSelector to fix import cycle
  frontend/src/components/App/themeSlice.ts
Labels: frontend, CI, cncf-cla: yes, approved, size/XS

#3192 frontend: Various multicluster fixes
  frontend/src/components/App/Home/ClusterTable.tsx
  frontend/src/components/App/Home/RecentClusters.tsx
  frontend/src/components/Sidebar/SidebarItem.tsx
  frontend/src/components/common/Link.tsx
  frontend/src/components/common/Resource/ResourceTable.tsx
  frontend/src/components/crd/CustomResourceDetails.tsx
  frontend/src/components/crd/CustomResourceInstancesList.tsx
  frontend/src/components/crd/CustomResourceList.tsx
  frontend/src/components/crd/Details.tsx
  frontend/src/components/crd/List.tsx
  frontend/src/components/gateway/GatewayDetails.tsx
  frontend/src/components/gateway/GatewayList.tsx
  frontend/src/components/ingress/Details.tsx
  frontend/src/components/ingress/List.tsx
  frontend/src/components/pod/Details.tsx
  frontend/src/components/pod/List.tsx
  frontend/src/components/role/BindingList.tsx
  frontend/src/components/storage/ClaimDetails.tsx
  frontend/src/components/storage/ClaimList.tsx
  frontend/src/components/storage/VolumeDetails.tsx
  frontend/src/components/storage/VolumeList.tsx
  frontend/src/components/webhookconfiguration/Details.tsx
  frontend/src/lib/cluster.ts
  frontend/src/lib/k8s/KubeObject.ts
  frontend/src/lib/k8s/api/v2/KubeList.test.ts
  frontend/src/lib/k8s/api/v2/KubeList.ts
  frontend/src/lib/k8s/api/v2/useKubeObjectList.ts
  frontend/src/lib/k8s/event.ts
  frontend/src/lib/router.tsx
Labels: kind/bug, kind/feature, frontend, lgtm, multi, cncf-cla: yes, approved, size/L

#2974 Headlamp Plugins CLI: Bulk installations support
  plugins/headlamp-plugin/README.md
  plugins/headlamp-plugin/bin/headlamp-plugin.js
  plugins/headlamp-plugin/dependencies-sync.js
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
  plugins/headlamp-plugin/plugin-management/multi-plugin-management.js
  plugins/headlamp-plugin/plugin-management/multi-plugin-management.test.js
  plugins/headlamp-plugin/plugin-management/plugin-management.js
Labels: plugins, headlamp-plugin, size:XL, lgtm, lxf, cncf-cla: yes, approved, size/XXL

#1603 frontend: add node shell
  app/package-lock.json
  frontend/src/components/App/Settings/NodeShellSettings.tsx
  frontend/src/components/App/Settings/SettingsCluster.tsx
  frontend/src/components/App/Settings/util.tsx
  frontend/src/components/node/Details.tsx
  frontend/src/components/node/NodeShellAction.tsx
  frontend/src/components/node/NodeShellTerminal.tsx
  frontend/src/helpers/clusterSettings.ts
  frontend/src/i18n/locales/de/glossary.json
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/glossary.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/glossary.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/glossary.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/it/glossary.json
  frontend/src/i18n/locales/it/translation.json
  frontend/src/i18n/locales/ja/glossary.json
  frontend/src/i18n/locales/ja/translation.json
  frontend/src/i18n/locales/ko/glossary.json
  frontend/src/i18n/locales/ko/translation.json
  frontend/src/i18n/locales/pt/glossary.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/glossary.json
  frontend/src/i18n/locales/zh-tw/translation.json
  frontend/src/i18n/locales/zh/glossary.json
  frontend/src/i18n/locales/zh/translation.json
  frontend/src/plugin/__snapshots__/pluginLib.snapshot
  frontend/src/redux/actionButtonsSlice.ts
Labels: size:XL, lgtm, cncf-cla: yes, size/XL, approved

#2976 LFX'25: Pkg Telemetry: Backend Otel Instrumentation
  backend/go.mod
  backend/go.sum
  backend/pkg/config/config.go
  backend/pkg/telemetry/README.md
  backend/pkg/telemetry/metrics.go
  backend/pkg/telemetry/metrics_test.go
  backend/pkg/telemetry/telemetry.go
  backend/pkg/telemetry/telemetry_test.go
  backend/pkg/telemetry/tracing.go
  backend/pkg/telemetry/tracing_test.go
Labels: backend, size:XXL, lxf, cncf-cla: yes, size/XXL

#3236 frontend: pod evict and force deletion
  frontend/src/components/App/Settings/Settings.tsx
  frontend/src/components/App/Settings/__snapshots__/Settings.General.stories.storyshot
  frontend/src/components/common/Resource/DeleteButton.tsx
  frontend/src/components/common/Resource/DeleteMultipleButton.tsx
  frontend/src/components/common/Resource/MainInfoSection/__snapshots__/MainInfoSection.Normal.stories.storyshot
  frontend/src/components/common/Resource/MainInfoSection/__snapshots__/MainInfoSection.NullBacklink.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.Error.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.Initializing.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.LivenessFailed.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.PullBackOff.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.Running.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.Successful.stories.storyshot
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/it/translation.json
  frontend/src/i18n/locales/ja/translation.json
  frontend/src/i18n/locales/ko/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
  frontend/src/i18n/locales/zh/translation.json
  frontend/src/lib/k8s/KubeObject.ts
  frontend/src/lib/k8s/api/v1/clusterRequests.ts
  frontend/src/lib/k8s/api/v1/deleteParameters.ts
  frontend/src/lib/k8s/api/v1/factories.ts
  frontend/src/lib/k8s/apiProxy/index.ts
  frontend/src/lib/k8s/pod.ts
  frontend/src/redux/clusterActionSlice.ts
  frontend/src/redux/configSlice.ts
Labels: cncf-cla: yes, approved, size/L

#3196 frontend: plugins: Bump vite to 6.3.5
  frontend/package-lock.json
  frontend/package.json
  frontend/src/plugin/__snapshots__/pluginLib.snapshot
  plugins/examples/app-menus/package-lock.json
  plugins/examples/change-logo/package-lock.json
  plugins/examples/cluster-chooser/package-lock.json
  plugins/examples/custom-theme/package-lock.json
  plugins/examples/customizing-map/package-lock.json
  plugins/examples/details-view/package-lock.json
  plugins/examples/dynamic-clusters/package-lock.json
  plugins/examples/headlamp-events/package-lock.json
  plugins/examples/pod-counter/package-lock.json
  plugins/examples/resource-charts/package-lock.json
  plugins/examples/sidebar/package-lock.json
  plugins/examples/tables/package-lock.json
  plugins/examples/ui-panels/package-lock.json
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: dependencies, security, cncf-cla: yes, approved, size/XXL

#3243 frontend: Update helm test snapshot
  charts/headlamp/tests/expected_templates/oidc-validator-overrides.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved

#3254 fix: Use HTTPS for Kubernetes Contributor Guide Link in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cncf-cla: yes, approved, size/XS

#3261 headlamp-plugin: Bump undici to 6.21.3
  plugins/headlamp-plugin/package-lock.json
Labels: dependencies, cncf-cla: yes, approved, size/XS

#3260 headlamp-plugin: 0.12.0-alpha.0
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: cncf-cla: yes, approved, size/XS

#3265 fix: import fix on ./frontend/storybook/main.ts
  frontend/.storybook/main.ts
Labels: cncf-cla: yes, approved, size/XS

#3259 frontend: /common : refactor some code for /common import
  frontend/src/components/App/CreateCluster/AddCluster.tsx
  frontend/src/components/App/Home/ClusterContextMenu.tsx
  frontend/src/components/App/Home/ClusterTable.tsx
  frontend/src/components/App/Home/index.tsx
  frontend/src/components/App/Notifications/List/List.tsx
  frontend/src/components/App/Notifications/Notifications.tsx
  frontend/src/components/App/PluginSettings/PluginSettings.tsx
  frontend/src/components/App/PluginSettings/PluginSettingsDetails.tsx
  frontend/src/components/App/Settings/NodeShellSettings.tsx
  frontend/src/components/App/VersionDialog.tsx
Labels: cncf-cla: yes, size/M

#3288 frontend: tabs: Add TSDoc comments for component and helpers
  frontend/src/components/common/Tabs.tsx
Labels: documentation, cncf-cla: yes, approved, size/M, Tabs

#2983 charts: Add headlamp-plugin sidecar for automated plugin management
  charts/headlamp/templates/deployment.yaml
  charts/headlamp/templates/plugin-configmap.yaml
  charts/headlamp/values.yaml
  docs/installation/in-cluster/index.md
  plugins/headlamp-plugin/README.md
  plugins/headlamp-plugin/bin/headlamp-plugin.js
  plugins/headlamp-plugin/plugin-management/multi-plugin-management.js
Labels: plugins, headlamp-plugin, lxf, cncf-cla: yes, approved, size/L

#3289 headlamp-plugin: 0.12.0-alpha.1
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: cncf-cla: yes, approved, size/XS

#3292 headlamp-plugin: Fix windows path issue with node polyfill
  plugins/headlamp-plugin/config/vite.config.mjs
Labels: cncf-cla: yes, approved, size/XS

#3164 frontend: Settings: Replace theme dropdown menu with grid-based selector
  frontend/src/components/App/Settings/Settings.tsx
  frontend/src/components/App/Settings/__snapshots__/Settings.General.stories.storyshot
Labels: cncf-cla: yes, approved, size/L

#3293 headlamp-plugin: 0.12.0-alpha.2
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: cncf-cla: yes, approved, size/XS

#3268 frontend: common: Refactoring imports for /common
  frontend/src/components/App/Settings/Settings.tsx
  frontend/src/components/App/Settings/SettingsButton.tsx
  frontend/src/components/App/Settings/SettingsCluster.tsx
  frontend/src/components/App/Settings/SettingsClusters.tsx
  frontend/src/components/storage/ClaimDetails.tsx
  frontend/src/components/storage/ClaimList.tsx
  frontend/src/components/storage/VolumeDetails.tsx
  frontend/src/components/storage/VolumeList.tsx
  frontend/src/components/verticalPodAutoscaler/Details.tsx
  frontend/src/components/verticalPodAutoscaler/List.tsx
Labels: lgtm, cncf-cla: yes, approved, size/M

#3094 frontend: Add 2 more default themes
  frontend/src/components/App/themeSlice.ts
Labels: lgtm, cncf-cla: yes, approved, size/M

#3295 frontend: Update Settings snapshot
  frontend/src/components/App/Settings/__snapshots__/Settings.General.stories.storyshot
Labels: cncf-cla: yes, approved, size/M

#3297 README: Add links to plugin repo and artifact hub
  README.md
Labels: cncf-cla: yes, approved, size/XS

#3298 frontend: notifications: Fix storybook crash due to missing context
  frontend/src/components/App/Notifications/List/List.stories.tsx
  frontend/src/redux/drawerModeSlice.ts
Labels: cncf-cla: yes, approved, size/XS

#3282 docs: Add guide for AKS cluster using Entra Login and Entra RBAC with OauthProxy2
  docs/installation/in-cluster/aks-cluster-oauth/index.md
Labels: documentation, AKS, cncf-cla: yes, approved, size/L

#3294 frontend Terminal: Add workaround for inputting pipe character
  frontend/src/components/common/Terminal.tsx
  frontend/src/components/node/NodeShellTerminal.tsx
Labels: frontend, blocker, lgtm, cncf-cla: yes, approved, size/M

#3248 Add Hindi language support
  frontend/src/i18n/config.ts
  frontend/src/i18n/locales/hi/app.json
  frontend/src/i18n/locales/hi/glossary.json
  frontend/src/i18n/locales/hi/translation.json
Labels: cncf-cla: yes, size/XL

#3300 frontend: i18n: Fix make frontend-i18n-check locales needed updating
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/it/translation.json
  frontend/src/i18n/locales/ja/translation.json
  frontend/src/i18n/locales/ko/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
  frontend/src/i18n/locales/zh/translation.json
Labels: kind/bug, i18n, lgtm, cncf-cla: yes, size/S, approved

#3235 frontend: NamespacesAutocomplete: Show list of selected namespaces while hovering
  frontend/src/components/common/NamespacesAutocomplete.tsx
  frontend/src/components/common/Table/__snapshots__/Table.NamespaceSelect.stories.storyshot
  frontend/src/components/common/__snapshots__/SimpleTable.NamespaceSelect.stories.storyshot
Labels: cncf-cla: yes, size/S, approved

#3220 frontend: hide managed fields
  frontend/src/components/common/Resource/EditButton.tsx
  frontend/src/components/common/Resource/EditorDialog.tsx
  frontend/src/components/common/Resource/ViewButton.tsx
  frontend/src/components/common/Resource/__snapshots__/ViewButton.ViewOpen.stories.storyshot
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/it/translation.json
  frontend/src/i18n/locales/ja/translation.json
  frontend/src/i18n/locales/ko/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
  frontend/src/i18n/locales/zh/translation.json
Labels: lgtm, cncf-cla: yes, approved, size/M

#3305 frontend: i18n: Update Hindi translations
  frontend/src/i18n/locales/hi/translation.json
Labels: cncf-cla: yes, approved, size/XS

#3309 headlamp-plugin: 0.12.0
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: cncf-cla: yes, approved, size/XS

#3313 docs: backend: Add missing make targets
  docs/development/backend.md
Labels: cncf-cla: yes, size/S, approved

#3302 SECURITY.md: Add security policy specific text
  SECURITY.md
Labels: security, cncf-cla: yes, approved, size/XS

#3314 plugins/examples/resource-charts: Add .gitignore
  plugins/examples/resource-charts/.gitignore
Labels: cncf-cla: yes, size/S, approved

#3316 frontend: common: Refactoring common/ imports in frontend directory
  frontend/src/components/deployments/List.tsx
  frontend/src/components/endpoints/Details.tsx
  frontend/src/components/resourceMap/GraphRenderer.tsx
  frontend/src/components/resourceMap/GraphView.tsx
  frontend/src/components/resourceMap/KubeObjectGlance/DeploymentGlance.tsx
  frontend/src/components/resourceMap/KubeObjectGlance/EndpointsGlance.tsx
  frontend/src/components/resourceMap/KubeObjectGlance/PodGlance.tsx
  frontend/src/components/resourceMap/KubeObjectGlance/ReplicaSetGlance.tsx
  frontend/src/components/resourceMap/KubeObjectGlance/ServiceGlance.tsx
  frontend/src/components/resourceMap/details/GraphNodeDetails.tsx
Labels: cncf-cla: yes, size/S, approved

#3325 frontend: NavigationTabs: Fix to use cloneDeep instead of structuredClone
  frontend/src/components/Sidebar/NavigationTabs.tsx
Labels: kind/bug, regression, blocker, cncf-cla: yes, approved, size/XS, Sidebar

#3277 frontend: Sidebar: Fix conditional expansion description text
  frontend/src/components/Sidebar/Sidebar.tsx
  frontend/src/components/Sidebar/__snapshots__/Sidebar.HomeSidebarClosed.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.HomeSidebarOpen.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarClosed.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarOpen.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.SelectedItemWithSidebarOmitted.stories.storyshot
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/it/translation.json
  frontend/src/i18n/locales/ja/translation.json
  frontend/src/i18n/locales/ko/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
  frontend/src/i18n/locales/zh/translation.json
Labels: cncf-cla: yes, size/S, approved

#3278 refactor: refactor the code to make the StartPortForward function sho…
  backend/pkg/portforward/handler.go
Labels: cncf-cla: yes, approved, size/L

#3328 frontend: i18n: Fix main branch merge issue
  frontend/src/i18n/locales/hi/translation.json
Labels: cncf-cla: yes, approved, size/XS

#3329 backend: Refactor portforward/handler_test.go TestStartPortForward
  backend/pkg/portforward/handler_test.go
Labels: cncf-cla: yes, approved, size/L

#3304 Backend: Improve cluster metadata and add clusterID
  backend/cmd/headlamp.go
  backend/pkg/kubeconfig/kubeconfig.go
  backend/pkg/kubeconfig/kubeconfig_test.go
  backend/pkg/kubeconfig/test_data/kubeconfig_metadata
  backend/pkg/kubeconfig/test_data/kubeconfig_metadata_duplicate
Labels: cncf-cla: yes, approved, size/L

#3330 frontend: Home: Display true kubeconfig origin
  frontend/src/components/App/Home/ClusterTable.tsx
Labels: cncf-cla: yes, approved, size/XS

#3284 backend: pkg: portforward: Fix cache implementation and refactor shorten PortForward
  backend/pkg/portforward/handler.go
  backend/pkg/portforward/handler_test.go
Labels: cncf-cla: yes, size/XL, approved, portforward

#3317 frontend: Overview and Charts: Storybook added
  frontend/src/components/workload/Charts.stories.tsx
  frontend/src/components/workload/Charts.tsx
  frontend/src/components/workload/Overview.stories.tsx
  frontend/src/components/workload/__snapshots__/Charts.AllFailedDeployment.stories.storyshot
  frontend/src/components/workload/__snapshots__/Charts.AllFailedStatefulSet.stories.storyshot
  frontend/src/components/workload/__snapshots__/Charts.AllRunningDeployment.stories.storyshot
  frontend/src/components/workload/__snapshots__/Charts.AllRunningStatefulSet.stories.storyshot
  frontend/src/components/workload/__snapshots__/Charts.DefaultDeployment.stories.storyshot
  frontend/src/components/workload/__snapshots__/Charts.DefaultStatefulSet.stories.storyshot
  frontend/src/components/workload/__snapshots__/Charts.Empty.stories.storyshot
  frontend/src/components/workload/__snapshots__/Charts.LoadingWorkload.stories.storyshot
  frontend/src/components/workload/__snapshots__/Charts.MixedWorkloads.stories.storyshot
  frontend/src/components/workload/__snapshots__/Overview.Workloads.stories.storyshot
Labels: cncf-cla: yes, approved, size/XXL

#3327 frontend: docs: Add TSDoc comments for component and helpers
  frontend/src/i18n/LocaleSelect/LocaleSelect.tsx
  frontend/src/i18n/ThemeProviderNexti18n.tsx
Labels: cncf-cla: yes, approved, size/M

#3319 frontend: improve Loader component and update Storybook examples
  frontend/src/components/common/EmptyContent.stories.tsx
  frontend/src/components/common/Loader.stories.tsx
  frontend/src/components/common/Loader.test.tsx
  frontend/src/components/common/Loader.tsx
  frontend/src/components/common/SectionHeader.stories.tsx
  frontend/src/components/common/SectionHeader.tsx
  frontend/src/components/common/__snapshots__/EmptyContent.Default.stories.storyshot
  frontend/src/components/common/__snapshots__/EmptyContent.Empty.stories.storyshot
  frontend/src/components/common/__snapshots__/EmptyContent.WithCustomColor.stories.storyshot
  frontend/src/components/common/__snapshots__/EmptyContent.WithMultipleChildren.stories.storyshot
  frontend/src/components/common/__snapshots__/Loader.CustomColor.stories.storyshot
  frontend/src/components/common/__snapshots__/Loader.CustomSize.stories.storyshot
  frontend/src/components/common/__snapshots__/Loader.DefaultWithContainer.stories.storyshot
  frontend/src/components/common/__snapshots__/Loader.InlineNoContainer.stories.storyshot
  frontend/src/components/common/__snapshots__/Loader.InsideAComponent.stories.storyshot
  frontend/src/components/common/__snapshots__/Loader.NoTitleProvided.stories.storyshot
  frontend/src/components/common/__snapshots__/SectionHeader.LabelStyle.stories.storyshot
  frontend/src/components/common/__snapshots__/SectionHeader.LongTitle.stories.storyshot
  frontend/src/components/common/__snapshots__/SectionHeader.MainStyle.stories.storyshot
  frontend/src/components/common/__snapshots__/SectionHeader.NoActionsOrSubtitle.stories.storyshot
  frontend/src/components/common/__snapshots__/SectionHeader.NormalStyle.stories.storyshot
  frontend/src/components/common/__snapshots__/SectionHeader.SubSectionStyle.stories.storyshot
  frontend/src/components/common/__snapshots__/SectionHeader.WithActions.stories.storyshot
  frontend/src/components/common/__snapshots__/SectionHeader.WithNoPadding.stories.storyshot
  frontend/src/components/common/__snapshots__/SectionHeader.WithReactNodeAsTitle.stories.storyshot
  frontend/src/components/common/__snapshots__/SectionHeader.WithTitleSideActions.stories.storyshot
Labels: cncf-cla: yes, approved, size/XXL

#3345 frontend: InnerTable: Add storybook stories
  frontend/src/components/common/InnerTable.stories.tsx
  frontend/src/components/common/__snapshots__/InnerTable.Default.stories.storyshot
  frontend/src/components/common/__snapshots__/InnerTable.EmptyTable.stories.storyshot
  frontend/src/components/common/__snapshots__/InnerTable.InsideAnotherComponent.stories.storyshot
  frontend/src/components/common/__snapshots__/InnerTable.WithFewRows.stories.storyshot
  frontend/src/components/common/__snapshots__/InnerTable.WithoutTableHeader.stories.storyshot
Labels: cncf-cla: yes, size/XL, approved

#3347 frontend: storybook: Added new story for Service/List
  frontend/src/components/service/ServiceList.stories.tsx
  frontend/src/components/service/__snapshots__/ServiceList.Default.stories.storyshot
  frontend/src/components/service/__snapshots__/ServiceList.Items.stories.storyshot
Labels: cncf-cla: yes, approved, size/XXL

#3342 frontend: lib/themes.ts: Add test for getThemeName
  frontend/src/lib/themes.test.ts
Labels: cncf-cla: yes, approved, size/M

#3355 frontend: common: Refactored all imports to their direct location
  frontend/src/components/App/Settings/DrawerModeSettings.tsx
  frontend/src/components/DetailsViewSection/DetailsViewSection.stories.tsx
  frontend/src/components/Sidebar/Sidebar.tsx
  frontend/src/components/authchooser/index.tsx
  frontend/src/components/cluster/Overview.tsx
  frontend/src/components/common/CreateResourceButton.tsx
  frontend/src/components/common/ObjectEventList.tsx
  frontend/src/components/crd/CustomResourceDetails.tsx
  frontend/src/components/crd/CustomResourceList.tsx
  frontend/src/components/crd/Details.tsx
  frontend/src/components/crd/List.tsx
  frontend/src/components/cronjob/Details.tsx
  frontend/src/components/cronjob/List.tsx
  frontend/src/components/daemonset/Details.tsx
  frontend/src/components/daemonset/List.tsx
  frontend/src/components/gateway/ClassList.tsx
  frontend/src/components/gateway/GatewayDetails.tsx
  frontend/src/components/gateway/HTTPRouteDetails.tsx
  frontend/src/components/gateway/HTTPRouteList.tsx
  frontend/src/components/gateway/utils.tsx
  frontend/src/components/horizontalPodAutoscaler/Details.tsx
  frontend/src/components/horizontalPodAutoscaler/List.tsx
  frontend/src/components/ingress/ClassList.tsx
  frontend/src/components/job/List.tsx
  frontend/src/components/lease/Details.tsx
  frontend/src/components/limitRange/Details.tsx
  frontend/src/components/limitRange/List.tsx
  frontend/src/components/namespace/CreateNamespaceButton.tsx
  frontend/src/components/namespace/List.tsx
  frontend/src/components/networkpolicy/Details.tsx
  frontend/src/components/node/Charts.tsx
  frontend/src/components/node/Details.tsx
  frontend/src/components/node/List.tsx
  frontend/src/components/node/NodeShellAction.tsx
  frontend/src/components/pod/Details.tsx
  frontend/src/components/pod/List.tsx
  frontend/src/components/pod/podDetailsVolumeSection.stories.tsx
  frontend/src/components/podDisruptionBudget/Details.tsx
  frontend/src/components/portforward/index.tsx
  frontend/src/components/priorityClass/Details.tsx
  frontend/src/components/replicaset/List.tsx
  frontend/src/components/resourceQuota/Details.tsx
  frontend/src/components/resourceQuota/List.tsx
  frontend/src/components/role/BindingDetails.tsx
  frontend/src/components/role/BindingList.tsx
  frontend/src/components/runtimeClass/Details.tsx
  frontend/src/components/secret/Details.tsx
  frontend/src/components/service/Details.tsx
  frontend/src/components/serviceaccount/Details.tsx
  frontend/src/components/statefulset/List.tsx
  frontend/src/components/webhookconfiguration/Details.tsx
Labels: cncf-cla: yes, approved, size/L

#3357 frontend: ServiceDetails: Adding story for Details
  frontend/src/components/service/ServiceDetails.stories.tsx
  frontend/src/components/service/__snapshots__/ServiceDetails.Default.stories.storyshot
  frontend/src/components/service/__snapshots__/ServiceDetails.Error.stories.storyshot
Labels: cncf-cla: yes, size/XL, approved

#3364 frontend: PodLogViewer: Scale down and Rename toggle buttons
  frontend/src/components/pod/Details.tsx
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/hi/translation.json
  frontend/src/i18n/locales/it/translation.json
  frontend/src/i18n/locales/ja/translation.json
  frontend/src/i18n/locales/ko/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
  frontend/src/i18n/locales/zh/translation.json
Labels: cncf-cla: yes, size/S, approved

#3331 frontend: Pod: Add prettify option for JSON Logs
  frontend/src/components/common/Resource/LogsButton.tsx
  frontend/src/components/pod/Details.tsx
  frontend/src/components/pod/PodLogs.stories.tsx
  frontend/src/components/pod/__snapshots__/PodLogs.BigJsonLogs.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodLogs.FormattedJsonLogs.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodLogs.FormattingLogs.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodLogs.JsonLogs.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodLogs.Logs.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodLogs.PlainLogs.stories.storyshot
  frontend/src/components/pod/jsonHandling.test.ts
  frontend/src/components/pod/jsonHandling.ts
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/hi/translation.json
  frontend/src/i18n/locales/it/translation.json
  frontend/src/i18n/locales/ja/translation.json
  frontend/src/i18n/locales/ko/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
  frontend/src/i18n/locales/zh/translation.json
  frontend/src/lib/k8s/pod.ts
Labels: cncf-cla: yes, approved, size/XXL

#3361 frontend: redux: Fix slices to export reducers for consistency
  frontend/src/components/resourceMap/graphViewSlice.tsx
  frontend/src/redux/reducers/reducers.tsx
  frontend/src/redux/uiSlice.ts
Labels: cncf-cla: yes, size/S, approved

#3360 frontend: lib/auth.ts: Add tests for getToken
  frontend/src/lib/auth.test.ts
Labels: cncf-cla: yes, approved, size/L

#3378 frontend: storybook: Add back full import to fix vite/storybook bug
  frontend/.storybook/preview.tsx
Labels: lgtm, cncf-cla: yes, approved, size/XS

#3371 frontend: Pod: Reorder unescaped string literals
  frontend/src/components/pod/PodLogs.stories.tsx
  frontend/src/lib/k8s/pod.ts
Labels: kind/bug, frontend, security, cncf-cla: yes, approved, size/XS

#3384 docs: eks: Clarify OIDC setup for non-Cognito and ingress users
  docs/installation/in-cluster/eks/index.md
Labels: documentation, oidc, blocker, cncf-cla: yes, size/S, approved

#3381 frontend: Enable details drawer by default
  frontend/src/components/App/Settings/__snapshots__/Settings.General.stories.storyshot
  frontend/src/components/common/Resource/DetailsDrawer.tsx
  frontend/src/redux/drawerModeSlice.ts
Labels: cncf-cla: yes, approved, size/XS

#3395 chocolatey: Bump Headlamp version to 0.31.0
  app/windows/chocolatey/headlamp.nuspec
  app/windows/chocolatey/tools/chocolateyinstall.ps1
Labels: cncf-cla: yes, approved, size/XS

#3400 charts: Bump Headlamp version to v0.31.0
  charts/headlamp/Chart.yaml
  charts/headlamp/tests/expected_templates/default.yaml
  charts/headlamp/tests/expected_templates/extra-args.yaml
  charts/headlamp/tests/expected_templates/extra-manifests.yaml
  charts/headlamp/tests/expected_templates/oidc-create-secret.yaml
  charts/headlamp/tests/expected_templates/oidc-directly-env.yaml
  charts/headlamp/tests/expected_templates/oidc-directly.yaml
  charts/headlamp/tests/expected_templates/oidc-external-secret.yaml
  charts/headlamp/tests/expected_templates/oidc-validator-overrides.yaml
  charts/headlamp/tests/expected_templates/volumes-added.yaml
Labels: cncf-cla: yes, approved, size/L

#3406 backend: Add missing space before token in the Authorization header in multiplexed websocket connection
  backend/cmd/multiplexer.go
Labels: kind/bug, backend, cncf-cla: yes, approved, size/XS

#3391 frontend: Update Code of Conduct link in docs
  docs/index.md
Labels: cncf-cla: yes, approved, size/XS

#3377 fix(codeSign) shell command built from environment values
  app/mac/scripts/codeSign.js
Labels: cncf-cla: yes, approved, size/XS
