Repository kubernetes-sigs/headlamp, pull requests merged in 2025-08, with the labels that each got.

#3730 backend: Remove unnecessary assignment in range for loop
  backend/cmd/headlamp.go
  backend/cmd/headlamp_test.go
  backend/cmd/stateless.go
  backend/cmd/stateless_test.go
  backend/pkg/helm/charts.go
  backend/pkg/helm/repository.go
  backend/pkg/helm/repository_test.go
  backend/pkg/kubeconfig/watcher.go
  backend/pkg/logger/logger_test.go
  backend/pkg/plugins/plugins_test.go
  backend/pkg/portforward/internal_test.go
Labels: cncf-cla: yes, size/S

#3727 backend: HeadlampServer: Move router initialization codes to createHeadlampHandler
  backend/cmd/headlamp.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#3741 backend: config: Refactor parse tests
  backend/pkg/config/config_test.go
Labels: backend, testing, cncf-cla: yes, approved, size/L

#3744 charts: Bump Headlamp version to v0.34.0
  charts/headlamp/Chart.yaml
  charts/headlamp/tests/expected_templates/azure-oidc-with-validators.yaml
  charts/headlamp/tests/expected_templates/default.yaml
  charts/headlamp/tests/expected_templates/extra-args.yaml
  charts/headlamp/tests/expected_templates/extra-manifests.yaml
  charts/headlamp/tests/expected_templates/non-azure-oidc.yaml
  charts/headlamp/tests/expected_templates/oidc-create-secret.yaml
  charts/headlamp/tests/expected_templates/oidc-directly-env.yaml
  charts/headlamp/tests/expected_templates/oidc-directly.yaml
  charts/headlamp/tests/expected_templates/oidc-external-secret.yaml
  charts/headlamp/tests/expected_templates/oidc-validator-overrides.yaml
  charts/headlamp/tests/expected_templates/volumes-added.yaml
Labels: cncf-cla: yes, approved, size/L

#3736 frontend: lib/k8s: Add TSDocs for functions
  frontend/src/lib/k8s/index.ts
Labels: documentation, frontend, cncf-cla: yes, size/S, approved

#3719 frontend: Label: Fix text wrapping issue for labels
  frontend/src/components/common/Label.stories/__snapshots__/StatusLabel.Error.stories.storyshot
  frontend/src/components/common/Label.stories/__snapshots__/StatusLabel.Success.stories.storyshot
  frontend/src/components/common/Label.stories/__snapshots__/StatusLabel.Warning.stories.storyshot
  frontend/src/components/common/Label.tsx
  frontend/src/components/deployments/__snapshots__/List.Deployments.stories.storyshot
  frontend/src/components/horizontalPodAutoscaler/__snapshots__/HPADetails.Default.stories.storyshot
  frontend/src/components/job/__snapshots__/JobList.Items.stories.storyshot
  frontend/src/components/namespace/__snapshots__/NamespaceDetails.Active.stories.storyshot
  frontend/src/components/namespace/__snapshots__/NamespaceList.Regular.stories.storyshot
  frontend/src/components/node/__snapshots__/List.Nodes.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.Error.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.Initializing.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.LivenessFailed.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.PullBackOff.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.Running.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodDetails.Successful.stories.storyshot
  frontend/src/components/pod/__snapshots__/PodList.Items.stories.storyshot
  frontend/src/components/podDisruptionBudget/__snapshots__/pdbDetails.Default.stories.storyshot
  frontend/src/components/storage/__snapshots__/ClaimDetails.Base.stories.storyshot
  frontend/src/components/storage/__snapshots__/ClaimList.Items.stories.storyshot
  frontend/src/components/storage/__snapshots__/VolumeDetails.Base.stories.storyshot
Labels: kind/bug, frontend, cncf-cla: yes, approved, size/L

#3681 Improve releaser check
  tools/releaser/src/commands/check.ts
  tools/releaser/src/index.ts
  tools/releaser/src/utils/github.ts
Labels: cncf-cla: yes, size/XL, approved

#3658 chore(docs): brew `--no-quarantine` kludge to resolve bad sig/corrupt binary error
  docs/installation/desktop/mac-installation.md
Labels: cncf-cla: yes, approved, size/XS

#3733 app: mac: Fix broken first load of clusters and plugins
  app/electron/main.ts
Labels: mac, app, regression, minikube, cncf-cla: yes, approved, size/L

#3760 frontend: ActionsNotifier: Fix contrast issue for all themes
  frontend/src/components/common/ActionsNotifier.tsx
  frontend/src/components/common/__snapshots__/ActionsNotifier.Some.stories.storyshot
Labels: a11y, cncf-cla: yes, approved, size/XS

#3756 gitignore: Add ignore for mac .DS_Store files
  .gitignore
Labels: mac, dx, cncf-cla: yes, approved, size/XS

#3024 ci: push Helm Chart to GHCR
  .github/workflows/helm-chart-release.yml
Labels: size:S, cncf-cla: yes, size/S

#3768 Update platforms.md
  docs/platforms.md
Labels: cncf-cla: yes, approved, size/XS

#3774 frontend: Table: Refactor handleRowClick for switches
  frontend/src/components/common/Table/Table.tsx
Labels: kind/bug, frontend, Table, regression, cncf-cla: yes, approved, size/M

#3752 helm: add custom annotations to service
  charts/headlamp/templates/service.yaml
  charts/headlamp/values.yaml
Labels: cncf-cla: yes, approved, size/XS

#3412 frontend: cluster: Add Overview stories
  frontend/src/components/cluster/Overview.stories.tsx
  frontend/src/components/cluster/__snapshots__/Overview.EmptyState.stories.storyshot
  frontend/src/components/cluster/__snapshots__/Overview.ErrorState.stories.storyshot
  frontend/src/components/cluster/__snapshots__/Overview.LoadingState.stories.storyshot
Labels: cncf-cla: yes, approved, size/XXL

#3806 frontend: Update storybook to 9.1.2
  frontend/.storybook/HeadlampTheme.js
  frontend/.storybook/main.ts
  frontend/.storybook/manager.js
  frontend/.storybook/preview.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.test.tsx
  frontend/src/components/common/CreateResourceButton.stories.tsx
  frontend/src/components/common/LogViewer.stories.tsx
  frontend/src/components/namespace/CreateNamespaceButton.stories.tsx
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: cncf-cla: yes, approved, size/XXL

#3792 frontend: ClusterTable: Add registerClusterStatus
  frontend/src/components/App/Home/ClusterTable.tsx
  frontend/src/plugin/__snapshots__/pluginLib.snapshot
  frontend/src/plugin/registry.tsx
  frontend/src/redux/clusterProviderSlice.ts
Labels: minikube, cncf-cla: yes, approved, size/M

#3826 backend(oidc): Add support for custom CA and skipping TLS verification
  backend/cmd/headlamp.go
  backend/cmd/headlamp_test.go
  backend/cmd/headlamp_testdata/ca.crt
  backend/cmd/server.go
  backend/pkg/config/config.go
  backend/pkg/config/config_test.go
  backend/pkg/config/test_data/invalid_ca.pem
  backend/pkg/config/test_data/valid_ca.pem
  backend/pkg/kubeconfig/kubeconfig.go
  backend/pkg/kubeconfig/kubeconfig_test.go
  backend/pkg/kubeconfig/test_data/kubeconfig_oidc_ca_data
  backend/pkg/kubeconfig/test_data/oidc_ca.pem
  docs/development/oidc.md
Labels: kind/feature, backend, security, auth, oidc, cncf-cla: yes, size/XL, approved

#3805 backend: fix responseWriter to support protocol switching
  backend/pkg/telemetry/metrics.go
  backend/pkg/telemetry/metrics_test.go
Labels: kind/bug, backend, regression, cncf-cla: yes, approved, size/M

#3830 frontend: LogViewer: Prevent search overlapping scroll
  frontend/src/components/common/LogViewer.tsx
Labels: kind/bug, frontend, cncf-cla: yes, approved, size/XS, LogsViewer

#3820 frontend: Bump cipher-base to 1.0.6
  frontend/package-lock.json
Labels: frontend, dependencies, security, cncf-cla: yes, size/S, approved

#3755 app: plugins: tools/releaser: Bump tmp to 0.2.5
  app/package-lock.json
  plugins/examples/app-menus/package-lock.json
  plugins/examples/change-logo/package-lock.json
  plugins/examples/cluster-chooser/package-lock.json
  plugins/examples/custom-theme/package-lock.json
  plugins/examples/customizing-map/package-lock.json
  plugins/examples/details-view/package-lock.json
  plugins/examples/dynamic-clusters/package-lock.json
  plugins/examples/headlamp-events/package-lock.json
  plugins/examples/pod-counter/package-lock.json
  plugins/examples/resource-charts/package-lock.json
  plugins/examples/sidebar/package-lock.json
  plugins/examples/tables/package-lock.json
  plugins/examples/ui-panels/package-lock.json
  plugins/pluginctl/package-lock.json
  plugins/pluginctl/package.json
  tools/releaser/package-lock.json
Labels: dependencies, security, plugins, app, headlamp-plugin, cncf-cla: yes, approved, size/L

#3494 backend: auth: Extract ParseClusterAndToken from headlamp.go
  backend/cmd/headlamp.go
  backend/cmd/headlamp_test.go
  backend/pkg/auth/auth.go
  backend/pkg/auth/auth_test.go
Labels: backend, auth, oidc, cncf-cla: yes, approved, size/L

#3827 plugins: Bump vite-plugin-static-copy to 2.3.2
  plugins/examples/app-menus/package-lock.json
  plugins/examples/change-logo/package-lock.json
  plugins/examples/cluster-chooser/package-lock.json
  plugins/examples/custom-theme/package-lock.json
  plugins/examples/customizing-map/package-lock.json
  plugins/examples/details-view/package-lock.json
  plugins/examples/dynamic-clusters/package-lock.json
  plugins/examples/headlamp-events/package-lock.json
  plugins/examples/pod-counter/package-lock.json
  plugins/examples/projects/package-lock.json
  plugins/examples/resource-charts/package-lock.json
  plugins/examples/sidebar/package-lock.json
  plugins/examples/tables/package-lock.json
  plugins/examples/ui-panels/package-lock.json
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: dependencies, security, plugins, headlamp-plugin, lgtm, cncf-cla: yes, approved, size/L

#3839 frontend: Sanitize Projects' names as we type
  frontend/src/components/project/NewProjectPopup.tsx
  frontend/src/components/project/projectUtils.ts
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/hi/translation.json
  frontend/src/i18n/locales/it/translation.json
  frontend/src/i18n/locales/ja/translation.json
  frontend/src/i18n/locales/ko/translation.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/ta/translation.json
  frontend/src/i18n/locales/zh-tw/translation.json
  frontend/src/i18n/locales/zh/translation.json
Labels: cncf-cla: yes, approved, size/M

#3810 frontend: k8s: Handle new k8s feature native sidecars
  frontend/src/lib/k8s/cluster.ts
  frontend/src/lib/k8s/pod.ts
Labels: kind/feature, frontend, k8s, lgtm, cncf-cla: yes, approved, size/M
