Repository kubernetes-sigs/headlamp, pull requests merged in 2025-03, with the labels that each got.

#2893 app: fix headless mode not running
  app/electron/main.ts
  backend/cmd/headlamp.go
Labels: bug, app, regression, blocker, size:S, lgtm

#2964 plugin/examples: Add update script
  plugins/examples/update-deps.sh
Labels: size:M

#2965 Update plugins deps
  plugins/examples/app-menus/package-lock.json
  plugins/examples/app-menus/package.json
  plugins/examples/change-logo/package-lock.json
  plugins/examples/change-logo/package.json
  plugins/examples/cluster-chooser/package-lock.json
  plugins/examples/cluster-chooser/package.json
  plugins/examples/details-view/package-lock.json
  plugins/examples/details-view/package.json
  plugins/examples/dynamic-clusters/package-lock.json
  plugins/examples/dynamic-clusters/package.json
  plugins/examples/headlamp-events/package-lock.json
  plugins/examples/headlamp-events/package.json
  plugins/examples/pod-counter/package-lock.json
  plugins/examples/pod-counter/package.json
  plugins/examples/resource-charts/package-lock.json
  plugins/examples/sidebar/package-lock.json
  plugins/examples/sidebar/package.json
  plugins/examples/tables/package-lock.json
  plugins/examples/tables/package.json
Labels: size:S

#2602 frontend Map: Allow plugins to customize the map
  docs/development/plugins/functionality/extending-the-map.md
  docs/development/plugins/functionality/images/map-rs-and-pods.png
  docs/development/plugins/functionality/images/node-with-an-icon.png
  docs/development/plugins/functionality/images/node-without-an-icon.png
  docs/development/plugins/functionality/images/source-picker-workloads.png
  docs/development/plugins/functionality/images/source-picker.png
  docs/development/plugins/functionality/index.md
  frontend/src/components/resourceMap/GraphView.stories.tsx
  frontend/src/components/resourceMap/GraphView.tsx
  frontend/src/components/resourceMap/__snapshots__/GraphView.BasicExample.stories.storyshot
  frontend/src/components/resourceMap/details/GraphNodeDetails.tsx
  frontend/src/components/resourceMap/details/KubeNodeDetails.tsx
  frontend/src/components/resourceMap/graph/graphGrouping.tsx
  frontend/src/components/resourceMap/graph/graphModel.tsx
  frontend/src/components/resourceMap/graphViewSlice.tsx
  frontend/src/components/resourceMap/kubeIcon/KubeIcon.tsx
  frontend/src/components/resourceMap/sources/GraphSourcesView.tsx
  frontend/src/plugin/__snapshots__/pluginLib.snapshot
  frontend/src/plugin/registry.tsx
  frontend/src/redux/reducers/reducers.tsx
  plugins/examples/customizing-map/.gitignore
  plugins/examples/customizing-map/.vscode/extensions.json
  plugins/examples/customizing-map/.vscode/settings.json
  plugins/examples/customizing-map/.vscode/tasks.json
  plugins/examples/customizing-map/README.md
  plugins/examples/customizing-map/package-lock.json
  plugins/examples/customizing-map/package.json
  plugins/examples/customizing-map/src/headlamp-plugin.d.ts
  plugins/examples/customizing-map/src/index.tsx
  plugins/examples/customizing-map/tsconfig.json
Labels: frontend, plugins, size:XL, lgtm, resourceMap

#2977 Fix failing CI
  frontend/src/components/common/TimezoneSelect/TimezoneSelect.stories.tsx
  frontend/src/components/common/TimezoneSelect/__snapshots__/TimezoneSelect.Default.stories.storyshot
  plugins/update-deps.sh
Labels: size:XS

#2981 headlamp-plugin: Fix building
  frontend/src/components/resourceMap/graphViewSlice.tsx
  frontend/src/redux/drawerModeSlice.ts
  frontend/src/redux/overviewChartsSlice.ts
  plugins/headlamp-plugin/vite-types.d.ts
Labels: size:XS, lgtm

#2980 Add root files for SIG UI alignment
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  OWNERS
  OWNERS_ALIASES
  README.md
  SECURITY_CONTACTS
  code-of-conduct.md
Labels: size:M, lgtm

#2001 plugins: Migrate plugins to vite
  .github/workflows/frontend.yml
  frontend/package.json
  frontend/src/plugin/index.ts
  plugins/examples/customizing-map/package-lock.json
  plugins/examples/customizing-map/package.json
  plugins/examples/dynamic-clusters/package-lock.json
  plugins/examples/dynamic-clusters/package.json
  plugins/examples/dynamic-clusters/src/index.tsx
  plugins/headlamp-plugin/bin/headlamp-plugin.js
  plugins/headlamp-plugin/config/.storybook/main.js
  plugins/headlamp-plugin/config/.storybook/manager.js
  plugins/headlamp-plugin/config/plugins-tsconfig.json
  plugins/headlamp-plugin/config/setupTests.js
  plugins/headlamp-plugin/config/storyshots/storyshots-test.ts
  plugins/headlamp-plugin/config/vite.config.mjs
  plugins/headlamp-plugin/config/webpack.config.js
  plugins/headlamp-plugin/dependencies-sync.js
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
  plugins/headlamp-plugin/patches/react-scripts+5.0.0.patch
  plugins/headlamp-plugin/template/package.json
  plugins/headlamp-plugin/template/src/headlamp-plugin.d.ts
  plugins/headlamp-plugin/template/src/storybook.test.tsx
  plugins/headlamp-plugin/test-headlamp-plugin.js
  plugins/headlamp-plugin/tsconfig.json
  plugins/headlamp-plugin/vite-types.d.ts
Labels: size:XL, lgtm

#2978 frontend: node: Display taint value in status
  frontend/src/components/node/List.tsx
  frontend/src/components/node/utils.tsx
  frontend/src/lib/k8s/node.ts
Labels: bug, frontend, size:S

#2998 headlamp-plugin: Bump to version 0.11.0
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: size:XS, lgtm

#3007 frontend: Remove beta label from Map link and move it up in the sidebar
  frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarClosed.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.InClusterSidebarOpen.stories.storyshot
  frontend/src/components/Sidebar/__snapshots__/Sidebar.SelectedItemWithSidebarOmitted.stories.storyshot
  frontend/src/components/Sidebar/useSidebarItems.ts
  frontend/src/i18n/locales/de/glossary.json
  frontend/src/i18n/locales/en/glossary.json
  frontend/src/i18n/locales/es/glossary.json
  frontend/src/i18n/locales/fr/glossary.json
  frontend/src/i18n/locales/it/glossary.json
  frontend/src/i18n/locales/pt/glossary.json
  frontend/src/i18n/locales/zh-tw/glossary.json
  frontend/src/lib/router.tsx
Labels: size:L, lgtm

#3005 frontend: backend: Update dependencies
  backend/go.mod
  backend/go.sum
  frontend/package-lock.json
Labels: backend, frontend, dependencies, size:S

#3006 frontend: Disable multiplexer due to an issue
  frontend/src/helpers/index.ts
Labels: size:XS

#2982 frontend: Open Custom Resources and Custom Resource Definition in a drawer
  frontend/src/components/common/Link.tsx
  frontend/src/components/common/Resource/DetailsDrawer.tsx
  frontend/src/components/crd/CustomResourceDetails.stories.tsx
  frontend/src/components/crd/CustomResourceDetails.tsx
  frontend/src/components/crd/Details.tsx
  frontend/src/components/crd/__snapshots__/CustomResourceDetails.ErrorGettingCR.stories.storyshot
  frontend/src/components/crd/__snapshots__/CustomResourceDetails.ErrorGettingCRD.stories.storyshot
  frontend/src/components/resourceMap/details/KubeNodeDetails.tsx
  frontend/src/redux/drawerModeSlice.ts
Labels: size:L, lgtm

#3004 Enable translations and enable Traditional Chinese locale
  frontend/src/components/App/Settings/NumRowsInput.tsx
  frontend/src/components/App/Settings/SettingsCluster.tsx
  frontend/src/i18n/ThemeProviderNexti18n.tsx
  frontend/src/i18n/config.ts
  frontend/src/i18n/locales/de/translation.json
  frontend/src/i18n/locales/en/translation.json
  frontend/src/i18n/locales/es/glossary.json
  frontend/src/i18n/locales/es/translation.json
  frontend/src/i18n/locales/fr/translation.json
  frontend/src/i18n/locales/it/translation.json
  frontend/src/i18n/locales/pt/glossary.json
  frontend/src/i18n/locales/pt/translation.json
  frontend/src/i18n/locales/zh-tw/glossary.json
  frontend/src/i18n/locales/zh-tw/translation.json
Labels: size:XL

#3016 headlamp-plugin: Bump to version 0.11.1
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: size:XS

#3029 Makefile: Fix run-backend on windows
  Makefile
Labels: size:XS

#3022 docs: publishing: Remove install of headlamp-plugin globally
  docs/development/plugins/publishing.md
Labels: size:XS

#3021 docs: publishing: Fix extensions for yml files
  docs/development/plugins/publishing.md
Labels: size:XS

#3033 headlamp-plugin: Update dependencies with audit fix
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: dependencies, security, headlamp-plugin, size:XS

#3032 Dockerfile: Update to alpine:3.20.6
  Dockerfile
  Dockerfile.plugins
Labels: dependencies, security, container, size:XS, lgtm

#3037 app/app-build-manifest: Bump prometheus to 0.5.0
  app/app-build-manifest.json
Labels: dependencies, app, prometheus, size:XS

#3038 headlamp-plugin: Allow to copy extra dist files into dist folder
  plugins/headlamp-plugin/bin/headlamp-plugin.js
Labels: size:XS

#3042 container: Update Prometheus plugin
  container/build-manifest.json
Labels: size:XS, lgtm

#3041 headlamp-plugin: Bump to version 0.11.3
  plugins/headlamp-plugin/package-lock.json
  plugins/headlamp-plugin/package.json
Labels: size:XS

#2991 Install platform-specific tarballs for plugins
  app/.gitignore
  app/electron/__tests__/test-data/artifacthub-pkg.yml
  app/electron/main.ts
  app/electron/plugin-management.test.ts
  app/electron/plugin-management.ts
  app/package-lock.json
  app/package.json
Labels: enhancement, plugins, app, size:XL, lgtm

#3045 chocolatey: Bump Headlamp version to 0.30.0
  app/windows/chocolatey/headlamp.nuspec
  app/windows/chocolatey/tools/chocolateyinstall.ps1
Labels: size:XS, lgtm

#3048 Makefile: adds `backend-lint-fix` command
  Makefile
Labels: size:XS, lgtm

#3051 frontend: EditorDialog: Show error reason on failure
  frontend/src/components/common/Resource/EditorDialog.tsx
Labels: enhancement, frontend, size:XS, lgtm
